name: nier_scripts_editor
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cross_file: ^0.3.3+1
  desktop_drop: ^0.3.3
  ezanimation: ^0.6.0
  flutter:
    sdk: flutter

  flutter_riverpod: ^1.0.4
  window_manager: ^0.2.7
  xml: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
