name: f_servo
description: File utility and scripts editor for Nier Automata

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "^3.7.3"

dependencies:
  archive: ^3.3.2
  audioplayers: ^1.2.0
  code_text_field: 1.0.2
  context_menus: ^1.0.2
  convert: ^3.1.1
  crclib: ^3.0.0
  cross_file: ^0.3.3+1
  desktop_drop: ^0.3.3
  euc: ^1.0.6+8
  file_picker: ^5.2.0
  flutter:
    sdk: flutter

  flutter_highlight: ^0.7.0
  flutter_launcher_icons: ^0.10.0
  flutter_window_close: ^0.2.2
  fluttertoast: ^8.0.9
  highlight: ^0.7.0
  image: ^3.2.2
  mutex: ^3.0.0
  path: ^1.8.2
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.15
  tuple: ^2.0.0
  uuid: ^3.0.6
  window_manager: ^0.2.7
  xml: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/
    - assets/logo/
    - assets/svgs/
    - assets/MrubyDecompiler/
    - assets/MrubyDecompiler/bins/
    - assets/MrubyDecompiler/bins/linux/
    - assets/MrubyDecompiler/bins/windows/
    - assets/MrubyDecompiler/mrbToRb/
    - assets/FontAtlasGenerator/
    - assets/bins/
    - assets/bins/vgmStream/
    - assets/effect/
    - assets/effect/textures/
    - assets/images/
    - assets/mcdFonts/
    - assets/mcdFonts/1/
    - assets/mcdFonts/2/
    - assets/mcdFonts/3/
    - assets/mcdFonts/4/
    - assets/mcdFonts/5/
    - assets/mcdFonts/6/
    - assets/mcdFonts/7/
    - assets/mcdFonts/8/
    - assets/mcdFonts/9/
    - assets/mcdFonts/10/
    - assets/mcdFonts/11/
    - assets/mcdFonts/19/
    - assets/mcdFonts/20/
    - assets/mcdFonts/35/
    - assets/mcdFonts/36/
    - assets/mcdFonts/37/
    - assets/entityThumbnails/

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Bold.ttf
        - asset: assets/fonts/FiraCode-Light.ttf
        - asset: assets/fonts/FiraCode-Medium.ttf
        - asset: assets/fonts/FiraCode-Regular.ttf
        - asset: assets/fonts/FiraCode-SemiBold.ttf
          weight: 700
    - family: CustomIconsFont
      fonts:
        - asset: assets/fonts/CustomIconsFont.ttf

flutter_icons:
  # to update icons run
  # > flutter pub run flutter_launcher_icons:main
  android: true
  ios: true
  image_path: "assets/logo/pod_logo.png"
  web:
    generate: true
  windows:
    generate: true
