name: nier_scripts_editor
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  context_menus: ^1.0.2
  crclib: ^3.0.0
  cross_file: ^0.3.3+1
  desktop_drop: ^0.3.3
  euc: ^1.0.6+8
  ezanimation: ^0.6.0
  file_picker: ^5.2.0
  flutter:
    sdk: flutter

  fluttertoast: ^8.0.9
  path: ^1.8.2
  shared_preferences: ^2.0.15
  tuple: ^2.0.0
  uuid: ^3.0.6
  window_manager: ^0.2.7
  xml: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/svgs/

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Bold.ttf
        - asset: assets/fonts/FiraCode-Light.ttf
        - asset: assets/fonts/FiraCode-Medium.ttf
        - asset: assets/fonts/FiraCode-Regular.ttf
        - asset: assets/fonts/FiraCode-Retina.ttf
        - asset: assets/fonts/FiraCode-SemiBold.ttf
          weight: 700
    - family: CustomIconsFont
      fonts:
        - asset: assets/fonts/CustomIconsFont.ttf
