name: f_servo
description: File utility and scripts editor for Nier Automata

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "^3.7.3"

dependencies:
  archive: ^3.4.9
  audioplayers: ^5.2.1
  code_text_field: ^1.1.0
  convert: ^3.1.1
  crclib: ^3.0.0
  cross_file: ^0.3.3+1
  csv: ^6.0.0
  desktop_drop: ^0.4.4
  euc: ^1.0.6+8
  file_picker: ^6.1.1
  flutter:
    sdk: flutter

  flutter_highlight: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_window_close: ^1.0.0
  fluttertoast: ^8.2.4
  highlight: ^0.7.0
  image: ^4.1.3
  mutex: ^3.0.0
  path: ^1.8.3
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  tuple: ^2.0.0
  url_launcher: ^6.2.2
  uuid: ^4.2.2
  webview_windows: ^0.4.0
  window_manager: ^0.3.7
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Bold.ttf
        - asset: assets/fonts/FiraCode-Light.ttf
        - asset: assets/fonts/FiraCode-Medium.ttf
        - asset: assets/fonts/FiraCode-Regular.ttf
        - asset: assets/fonts/FiraCode-SemiBold.ttf
          weight: 700
    - family: CustomIconsFont
      fonts:
        - asset: assets/fonts/CustomIconsFont.ttf
  assets:
    - assets/
    - assets/logo/
    - assets/svgs/
    - assets/MrubyDecompiler/
    - assets/MrubyDecompiler/bins/
    - assets/MrubyDecompiler/bins/linux/
    - assets/MrubyDecompiler/bins/windows/
    - assets/MrubyDecompiler/mrbToRb/
    - assets/FontAtlasGenerator/
    - assets/bins/
    - assets/bins/vgmStream/
    - assets/effect/
    - assets/effect/model_thumbnails/
    - assets/effect/texture_thumbnails/
    - assets/images/
    - assets/mcdFonts/
    - assets/entityThumbnails/
    - assets/monaco_editor/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/base/browser/ui/codicons/codicon/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/base/common/worker/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/base/worker/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/abap/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/apex/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/azcli/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/bat/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/bicep/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/cameligo/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/clojure/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/coffee/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/cpp/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/csharp/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/csp/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/css/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/cypher/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/dart/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/dockerfile/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/ecl/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/elixir/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/flow9/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/freemarker2/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/fsharp/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/go/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/graphql/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/handlebars/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/hcl/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/html/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/ini/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/java/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/javascript/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/julia/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/kotlin/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/less/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/lexon/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/liquid/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/lua/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/m3/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/markdown/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/mdx/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/mips/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/msdax/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/mysql/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/objective-c/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/pascal/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/pascaligo/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/perl/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/pgsql/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/php/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/pla/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/postiats/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/powerquery/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/powershell/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/protobuf/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/pug/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/python/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/qsharp/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/r/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/razor/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/redis/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/redshift/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/restructuredtext/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/ruby/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/rust/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/sb/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/scala/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/scheme/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/scss/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/shell/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/solidity/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/sophia/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/sparql/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/sql/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/st/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/swift/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/systemverilog/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/tcl/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/twig/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/typescript/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/typespec/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/vb/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/wgsl/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/xml/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/basic-languages/yaml/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/editor/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/language/css/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/language/html/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/language/json/
    - assets/monaco_editor/node_modules/monaco-editor/min/vs/language/typescript/

flutter_icons:
  # to update icons run
  # > flutter pub run flutter_launcher_icons:main
  android: true
  ios: true
  image_path: "assets/logo/pod_logo.png"
  web:
    generate: true
  windows:
    generate: true
