name: f_servo
description: File utility and scripts editor for Nier Automata

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: "^3.7.3"

dependencies:
  archive: ^3.4.9
  args: ^2.6.0
  audioplayers: ^6.1.0
  code_text_field: ^1.1.0
  convert: ^3.1.1
  crclib: ^3.0.0
  cross_file: ^0.3.3+1
  csv: ^6.0.0
  desktop_drop: ^0.5.0
  dotted_border: ^2.1.0
  euc: ^1.0.6+8
  file_picker: ^8.1.3
  flutter:
    sdk: flutter

  flutter_highlight: ^0.7.0
  flutter_launcher_icons: ^0.14.1
  flutter_window_close: ^1.0.0
  fluttertoast: ^8.2.4
  highlight: ^0.7.0
  http: ^1.2.2
  image: ^4.1.3
  mutex: ^3.0.0
  path: ^1.8.3
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  test: ^1.25.7
  texture_rgba_renderer:
    git:
      url: https://github.com/ArthurHeitmann/flutter_texture_rgba_renderer
      ref: 14ea023afda67ffb11d877deb7e5f3056ab865d6
  tuple: ^2.0.0
  url_launcher: ^6.2.2
  uuid: ^4.4.2
  # webview_windows: ^0.4.0
  webview_windows:
    git:
      url: https://github.com/Channing-dong/flutter-webview-windows
      ref: 999601052534f30fb50045819ef3813dbb04b9b8
  window_manager: ^0.4.3
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  ffigen: ^16.1.0

flutter:

  uses-material-design: true

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Bold.ttf
        - asset: assets/fonts/FiraCode-Light.ttf
        - asset: assets/fonts/FiraCode-Medium.ttf
        - asset: assets/fonts/FiraCode-Regular.ttf
        - asset: assets/fonts/FiraCode-SemiBold.ttf
          weight: 700
    - family: CustomIconsFont
      fonts:
        - asset: assets/fonts/CustomIconsFont.ttf
  assets:
    - assets/
    - assets/logo/
    - assets/svgs/
    - assets/bins/
    - assets/bins/vgmStream/
    - assets/images/

flutter_icons:
  # to update icons run
  # > flutter pub run flutter_launcher_icons:main
  android: true
  ios: true
  image_path: "assets/logo/pod_logo.png"
  web:
    generate: true
  windows:
    generate: true

ffigen:
  # > dart run ffigen
  name: RustyPlatinumUtils
  exclude-all-by-default: true
  output: lib/ffi/RustyPlatinumUtilsFfi.dart
  headers:
    entry-points:
      - assets/rusty_platinum_utils/target/rusty_platinum_utils.h
  functions:
    include:
      - "rpu_.*"
