// ignore_for_file: constant_identifier_names, dangling_library_doc_comments
/// Flutter icons CustomIconsFont
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIconsFont
///      fonts:
///       - asset: fonts/CustomIconsFont.ttf
///
/// 
///

import 'package:flutter/widgets.dart';

class CustomIconsFont {
  CustomIconsFont._();

  static const _kFontFam = 'CustomIconsFont';
  static const String? _kFontPkg = null;

  static const IconData sphere = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cylinder = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cube = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radius = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customCue2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customCue = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exitCue = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exitCue2 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entryCue2 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entryCue = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customCue2_rounded = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exitCue_rounded = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customCue_rounded = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entryCue_rounded = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entryCue2_rounded = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exitCue2_rounded = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
