import 'dart:collection';

final Map<String, String> japToEng = HashMap<String, String>.from({
  " 倉庫セキュリティ　解除 ": "Warehouse Security　Cancellation ",
  "000 石・コンクリート": "000 Stone/Concrete",
  "001 金属 ソリッド": "001 Metal solid",
  "001 金属 プレート": "001 Metal plate",
  "001 金属 ホロウ": "001 Metal Hollow",
  "002 木 ソリッド": "002 Wood solid",
  "003 草": "003 Grass",
  "004 土": "004Sat",
  "005 砂": "005 Sand",
  "006 プラスチック": "006 Plastic",
  "007 ガラス": "007 Glass",
  "008 水": "008 Water",
  "010 絨毯": "010 Carpet",
  "011 肉": "011 Meat",
  "012 果物": "012 Fruits",
  "013 機械": "013 Machinery",
  "014 土のう": "014 Sandbag",
  "015 特殊壁　(透明壁・特定以外使用不可)": "015 Special Wall　( Transparent wall/Cannot be used except in certain areas )",
  "016 水 深い 歩行可": "016 Water deep Walkable",
  "017 水 浅い 水溜まり": "017 Water shallow Puddle",
  "1ステージ 1-1 スフミ市街地 【共通】 壁登り屋内": "1 Stage 1-1 Sukhumi City 【 common 】 Climbing wall indoors",
  "1ステージ 1-1 スフミ市街地 【共通】 強風": "1 Stage 1-1 Sukhumi City 【 common 】 Strong winds",
  "1ステージ 1-1 スフミ市街地 【共通】 浜辺": "1 Stage 1-1 Sukhumi City 【 common 】 beach",
  "3ステガラス割れの風吹き込みSEエリアのオンオフ": "3 stage glass breaking wind blowing sound effect area on/off",
  "3ステモールエリアのオンオフ": "3. Stem Area On/Off",
  "3ステ屋上エリアのオンオフ": "the 3- story rooftop area on and off",
  "3ステ都市道路エリアのオンオフ": "3- stage city road area",
  "4ステエントランスSEエリアのオンオフ": "4th stage entrance SE area on/off",
  "4ステエントランスガラス割れの風吹き込みSEエリアのオンオフ": "4th stage entrance glass breaking wind blowing sound effect area on/off",
  "4ステオフィス奥の部屋ガラス割れの風吹き込みSEエリアのオンオフ": "4. Office back room glass breaking wind blowing sound effect area on/off",
  "4ステオフィス廊下ガラス割れの風吹き込みSEエリアのオンオフ": "4. Office corridor glass breaking wind blowing sound effect area on/off",
  "4ステオフィス手前の部屋ガラス割れの風吹き込みSEエリアのオンオフ": "4. Wind-blowing sound effect area for glass-breaking in the room in front of the office",
  "4ステ屋上雷のみのエリアのオンオフ": "4th floor rooftop lightning only area on/off",
  "BGM音量によって環境音をダッキングするためのパラメータ": "Parameter for ducking environmental sounds according to BGM volume",
  "Browning M2 機銃発射": "Browning M2 machine gun firing",
  "Courtney 流用": "Courtney",
  "DLC1 VR RAY 看板": "DLC1 VR RAY Signboard",
  "DLC1 VR pe24 BPキューブ": "DLC1 VR pe24 BP Cube",
  "DLC1 pe40 >>GO表示のSE": "DLC1 pe40 >> GO display SE",
  "DLC2 PC40_ELV rc15 エレベータ": "DLC2 PC40_ELV rc15 elevator",
  "DLC2サムの挑発音声のステージ切替など": "DLC2 Sam's provocation voice stage change etc.",
  "EMPグレネード": "EMP Grenade",
  "EV4030の入り口なので何もしないこと": "EV4030 , so do nothing.",
  "MG-Ray 再生スタートはこのEventでなく登場デモに入れている": "MG-Ray playback start is included in the appearance demo, not in this Event",
  "P110 ビーチ建物　倒壊": "P110 Beach Building　collapse",
  "PA15 ホテル柱　倒壊": "PA15 Hotel Pillar　collapse",
  "PA15 兵士突撃　壁壊れ": "PA15 Soldier Assault　Wall broken",
  "PA15 岩壁倒壊": "PA15 rock wall collapse",
  "PGLevelMeterオンオフ用": "For turning PGLevelMeter on and off",
  "QTE RAY切断": "QTE RAY CUTTING",
  "QTE RAY咆哮〜切断": "QTE RAY Roar ~ Cut",
  "QTE RAY裂ける": "QTE RAY split",
  "RAY ダメージ 中": "RAY Damage Medium",
  "RAY ダメージ　小": "RAY Damage Small",
  "RAY ダメージ　打率低": "RAY Damage　Low batting average",
  "RAY ダメージ　電気　小": "RAY Damage　Small Electric",
  "RAY ミサイル発射": "RAY missile launch",
  "RAY 予兆　鳴き声": "RAY Premonition　cry",
  "RAY 切断面　スパーク": "RAY cutting surface　spark",
  "RAY 叫び　小": "RAY scream small",
  "RAY 尻尾　切断": "RAY tail　Disconnect",
  "RAY 死亡　叫び": "RAY Dies　Scream",
  "RAY 稼働音 小1": "RAY operation sound Small 1",
  "RAY 稼働音 小2": "RAY operation sound Grade 2",
  "RAY 稼働音 小3": "RAY operation sound Grade 3",
  "RAY 稼働音 小4": "RAY operation sound Grade 4",
  "RAY 稼働音 小5": "RAY operation sound Grade 5",
  "RAY 稼働音 小6": "RAY operation sound 6th grade",
  "RAY 稼働音 小7": "RAY operation sound Grade 7",
  "RAY 稼働音 遅": "RAY operation sound Slow",
  "RAY 稼働音　小": "RAY operation noise is low",
  "RAY 腕　カバー閉まる": "RAY arm cover closes",
  "RAY 腕　カバー開く": "RAY arm cover open",
  "RAY 足爆発": "RAY's foot explodes",
  "RAY　ジャンプ　着地": "RAY　Jump　Landing",
  "RAY　ジャンプ　開始": "RAY　Jump　start",
  "RAY　ダウン": "RAY　down",
  "RAY　バックステップ": "RAY　Back Steps",
  "RAY　ミサイル爆発": "RAY　Missile Explosion",
  "RAY　ミサイル通過音": "RAY　Missile passing sound",
  "RAY　レーザー　地面hit": "RAY　Laser ground hit",
  "RAY　レーザー停止　シーケンスでトリガー": "RAY　Laser stop　Triggering with Sequence",
  "RAY　レーザー溜め": "RAY　Laser storage",
  "RAY　レーザー発射LOOP　sebulletでトリガー": "RAY　Laser firing LOOP　Triggered by sebullet",
  "RAY　叫び　中": "RAY　Screaming",
  "RAY　叫び　大": "RAY　Scream loud",
  "RAY　噛みつきorダウン　地面衝撃音": "RAY　Bite or down　Ground impact sound",
  "RAY　尻尾＆腕　地面削り音": "RAY　Tail & arms　Ground scraping sound",
  "RAY　岩　落ちる": "RAY rocks falling",
  "RAY　投げられ時　風切り音": "RAY　When thrown　Wind noise",
  "RAY　攻撃　地面削り破壊　ストップ": "RAY　attack　Ground scraping destruction　stop",
  "RAY　稼働音　中": "RAY　Operating sound",
  "RAY　稼働音　小": "RAY　Low operating noise",
  "RAY　肩銃　閉じる": "RAY　Shoulder gun　close",
  "RAY　肩銃　開く": "RAY　Shoulder gun　open",
  "RAY　腕切断": "RAY　Arm amputation",
  "RAY　腕叩きつけ攻撃": "RAY　Arm slam attack",
  "RAY　腕振り　大": "RAY　Large arm swing",
  "RAY　腕振り　小": "RAY　Small arm swing",
  "RAY　腕掴まれ1": "RAY's arm is grabbed 1",
  "RAY　腕掴まれ2": "RAY's arm is grabbed 2",
  "RAY　腕掴まれ火花　停止": "RAY　My arm is grabbed and sparks fly　Stop",
  "RAY　腕爆発": "RAY　Arm Explosion",
  "RAY　腕爆発　大": "RAY　Arm Explosion",
  "RAY　腕爆発　小": "RAY　Small Arm Explosion",
  "RAY　腕破壊": "RAY　Arm destruction",
  "RAY　足銃　閉じる": "RAY　Foot Gun　close",
  "RAY　足銃　開く": "RAY　Foot Gun　open",
  "RAY　足音 走り": "RAY　footsteps Running",
  "RAY　足音　停止": "RAY　footsteps　Stop",
  "RAY　足音　歩き": "RAY　footsteps　Walking",
  "RAY　踏みつけ": "RAY　Trampling",
  "RAY　銃発射　肩＆足　": "RAY　Gun Firing　Shoulders & Legs　",
  "RAY　雄叫び　中": "RAY　Roaring",
  "RAY　雄叫び　大": "RAY　Roaring loud",
  "RAY戦 広場 鐘の塔": "RAY Battle Square Bell tower",
  "RPG リロード　敵": "RPG Reload Enemy",
  "RPG-7 撃つ": "RPG-7 Shooting",
  "RPG-7 爆発": "RPG-7 explosive",
  "RPG-7 通過音": "RPG-7 passing sound",
  "RPG-7　構える": "RPG-7　Get Ready",
  "RPG-7　構え下ろす": "RPG-7　Lower your stance",
  "RPG　リロード　雷電": "RPG　Reload　Raiden",
  "Radio Option 1018 　雷電ボイス　ミュート解除": "Radio Option 1018　Raiden Voice　Unmute",
  "Radio Option 1018　雷電ボイス　ミュート化": "Radio Option 1018　Raiden Voice　Muting",
  "Raiden 1014 Force(Bug? 日本語空行)": "Raiden 1014 Force ( Bug? Japanese blank line )",
  "Raiden 1014 Force　（Bug)": "Raiden 1014 Force ( Bug)",
  "Ray戦　建物　燃える": "Ray Battle　building　Burning",
  "Ray戦後　地面　燃える": "Ray Post-war　ground　Burning",
  "Ray戦後　地面　燃える ストップ": "Ray Post-war　ground　Burning stop",
  "SE: ENV: 環境音": "SE: ENV: Environmental sound",
  "SEをPAUSEする　pause_in / pause_out     radio_in / radio_out": "PAUSE SE　pause_in / pause_out     radio_in / radio_out",
  "SEをRESUMEする　pause_in / pause_out     radio_in / radio_out": "Resume a system engineer　pause_in / pause_out     radio_in / radio_out",
  "SE実装あり": "SE implementation",
  "SE実装あり 万一\"bgm_pc20_WOLF_exit\"が呼ばれなかった場合の保険 ": "SE implementation Insurance in case \"bgm_pc20_WOLF_exit\" is not called ",
  "TGS ROM エンドスレート遷移用": "TGS ROM end slate transition",
  "TOWミサイル　爆発": "TOW Missile　explosion",
  "TOWミサイル　爆発 pa40賑やかし専用": "TOW Missile　Explosion PA40 for entertainment purposes only",
  "TOWミサイル　発射": "TOW Missile　firing",
  "TOWミサイル　通過": "TOW Missile　Passing",
  "VR ブラン登場ステージ　ブランの水音を停止": "VR Bran Appearance Stage　Stop the water noise of Bran",
  "VR 入る": "Enter VR",
  "VR 切断　エフェクト": "VR Disconnect　effect",
  "VR　キューブ　出現": "VR　Cube　Appearance",
  "VR画面　カーソル音": "VR screen　Cursor Sound",
  "VR画面　入る　ウィンドウ　ウィンドウ表示": "VR screen　enter　window　Window Display",
  "VR画面　決定音": "VR screen　Decision sound",
  "collection画面 表示": "Collection screen display",
  "iai の終了時": "iai At the end of",
  "pl メイン武器": "pl main weapon",
  "pl　ボス武器": "pl　Boss Weapons",
  "r112　月光初登場　セミ鳴き": "r112　Moonlight's first appearance　Cicadas chirping",
  "r11e カタコンベ 床崩れ ": "r11e Catacombs Floor collapse ",
  "ra44 (旧ra42)": "ra44 ( formerly ra42)",
  "vrミッション時　増援　おかわり　登場": "vr missions　Reinforcements　Refill　Appearance",
  "●DLC2 Wolf (Die)": "●DLC2 Wolf (Die)",
  "●DLC2 Wolf (Game)": "●DLC2 Wolf (Game)",
  "いたぞ": "There it is",
  "かもめ鳴き声": "Seagulls crying",
  "このサブフェーズから始めるとムービーになる。ムービー内で同じ内容のBGM Eventを呼んでいるので、ここでは何もしない。書いてもムービー前にbgm_r300.bnkが一旦アンロードされるので即キャンセルされる。": "If you start from this subphase, it will become a movie. Since the movie calls a BGM Event with the same content, nothing will be done here. Even if you write it, it will be canceled immediately because bgm_r300.bnk will be unloaded once before the movie.",
  "アイテム　出現": "item　Appearance",
  "アイテム　取得": "item　Acquisition",
  "アイテム　回復系　使用": "item　Recovery　use",
  "アイテム　電解パック　使用": "item　Electrolysis Pack　use",
  "アイテムボックス　開く": "Item Box　open",
  "アサルトライフル 弾倉引き抜く": "Assault Rifle Pull out the magazine",
  "アサルトライフル　ハンドリング": "Assault Rifle　handling",
  "アサルトライフル　マガジン入れる": "Assault Rifle　Insert magazine",
  "アサルトライフル　マガジン取り外す": "Assault Rifle　Remove the magazine",
  "アサルトライフル　マガジン捨てる": "Assault Rifle　Throw away the magazine",
  "アサルトライフル　構え": "Assault Rifle　Stance",
  "アサルトライフル　構え下ろす": "Assault Rifle　Lower your stance",
  "アサルトライフル　発砲": "Assault Rifle　Firing",
  "アブハジア人市民 b": "Abkhazian citizens b",
  "アブハジア人市民　a": "Abkhazian citizens　a",
  "アブハジア市民　ダウン　小": "Citizens of Abkhazia　Down Small",
  "アブハジア市民　声　安堵": "Abkhazia citizens voice relief",
  "アブハジア市民　声　怯え": "Abkhazian citizens express fear",
  "アブハジア市民　声　恐れ": "Abkhazia citizens voice fear",
  "アブハジア市民　声　死亡": "Abkhazia Citizen Voice Death",
  "アブハジア市民　服　切断": "Abkhazia civil uniform cut off",
  "アブハジア市民　衣擦れ": "Citizens of Abkhazia　Rubbing clothes",
  "アブハジア市民　足音　擦り足": "Citizens of Abkhazia　footsteps　Scraping feet",
  "アブハジア市民　足音　歩き": "Citizens of Abkhazia　footsteps　Walking",
  "アブハジア市民　足音　裸足　切り替え": "Citizens of Abkhazia　footsteps　barefoot　switching",
  "アブハジア市民　足音　走り": "Citizens of Abkhazia　footsteps　Running",
  "ウルフ　すり足": "Wolf　Sliding feet",
  "ウルフ　ガード　中": "Wolf　Guarding",
  "ウルフ　ガード　小": "Wolf　Small guard",
  "ウルフ　ジャンプ　中": "Wolf　During the jump",
  "ウルフ　ジャンプ　小": "Wolf　Jump Small",
  "ウルフ　ステルスキル　 尻尾突き刺し": "Wolf　Stealth Kill　 Tail stabbing",
  "ウルフ　ステルスキル　尻尾　サーボ＆ムーブメント": "Wolf　Stealth Kill　tail　Servos & Movements",
  "ウルフ　ステルスキル　尻尾　突き刺し　風切り": "Wolf　Stealth Kill　tail　Piercing　Wind cutting",
  "ウルフ　ステルスキル　月光頭部　着地": "Wolf　Stealth Kill　Moonlight Head　Landing",
  "ウルフ　ステルスキル　頭部　チェーンソー突き指し": "Wolf　Stealth Kill　head　Chainsaw Pointing",
  "ウルフ　ダウン　中": "Wolf　Down",
  "ウルフ　ダウン　小": "Wolf　Down Small",
  "ウルフ　チェーンソー　ヒット　地面": "Wolf　Chainsaw Hit　ground",
  "ウルフ　チェーンソー　ヒット　機械": "Wolf　Chainsaw Hit　machine",
  "ウルフ　チェーンソー　ヒット　肉": "Wolf　Chainsaw hits meat",
  "ウルフ　チェーンソー　取り付け": "Wolf　Chainsaw installation",
  "ウルフ　チェーンソー　取り外し": "Wolf　Chainsaw removal",
  "ウルフ　チェーンソー　起動持続音　斬撃時": "Wolf　Chainsaw start-up sound　When slashing",
  "ウルフ　チェーンソー　起動持続音　斬撃時　ストップ": "Wolf　Chainsaw start-up sound　When slashing　stop",
  "ウルフ　チェーンソー　起動音": "Wolf　Chainsaw startup sound",
  "ウルフ　チェーンソー　起動音　ストップ": "Wolf　Chainsaw startup sound　stop",
  "ウルフ　チェーンソー　起動音　ストップ　回転弱まる": "Wolf　Chainsaw startup sound　stop　Rotation weakens",
  "ウルフ　チェーンソー　風切り　中": "Wolf　Chainsaw cutting",
  "ウルフ　チェーンソー　風切り　大": "Wolf　Chainsaw Wind Saw Large",
  "ウルフ　チェーンソー　風切り　小": "Wolf　Chainsaw Wind Cutter Small",
  "ウルフ　奪　ステルスキル時　敵から尻尾抜く": "Wolf stealth kill　Remove the tail from the enemy",
  "ウルフ　尻尾　ムーブメント": "Wolf　tail　Movement",
  "ウルフ　尻尾　風切り　中": "Wolf　tail　During wind cutting",
  "ウルフ　尻尾　風切り　大": "Wolf　tail　Large windbreaker",
  "ウルフ　尻尾　風切り　小": "Wolf　tail　Small windbreaker",
  "ウルフ　歩き": "Wolf　Walking",
  "ウルフ　歩き　足音単発": "Wolf　Walking　Single Footstep",
  "ウルフ　爪　ヒット　機械": "Wolf Claw Hit　machine",
  "ウルフ　爪　ヒット　肉": "Wolf claws hit meat",
  "ウルフ　爪　風切り　中": "Wolf nail clipping",
  "ウルフ　爪　風切り　小": "Wolf Nail Clipper Small",
  "ウルフ　着地　中": "Wolf　Landing",
  "ウルフ　着地　小": "Wolf　Small landing",
  "ウルフ　衣擦れ　中": "Wolf　Rubbing clothes",
  "ウルフ　衣擦れ　小": "Wolf　Clothes Rubbing Small",
  "ウルフ　走り": "Wolf　Running",
  "ウルフ　走り　滑り　中": "Wolf　Running　Sliding",
  "ウルフ　走り　滑り　小": "Wolf　Running　Small slip",
  "ウルフ　走り　足音単発": "Wolf　Running　Single Footstep",
  "エクセルサス　パーツ投げ爆発": "Excelsus　Parts Throwing Explosion",
  "エントランス　ハンマーヘッド　ブレイク": "entrance　Hammerhead　break",
  "オーグメントモード　入る": "Augmented Mode　enter",
  "オーグメントモード　出る": "Augmented Mode　Go out",
  "オーバーヒート　終了　ソフト呼び出し 不要？": "overheat　end　Soft Call Not needed ?",
  "オーバーヒート　開始　ソフト呼び出し 不要？": "overheat　start　Soft Call Not needed ?",
  "カスタマイズ画面　アイテム 購入　強化　決定": "Customization screen　item purchase　Enhancement　Decision",
  "カスタマイズ画面　アイテム　ポイント足りない　エラー": "Customization screen　item　Not enough points　error",
  "カスタマイズ画面　アイテム　強化": "Customization screen　item　Enhancement",
  "カスタマイズ画面　アイテム　装備": "Customization screen　item　Equipment",
  "カスタマイズ画面　アイテムウィンドウ カーソル音": "Customization screen　Items Window Cursor Sound",
  "カスタマイズ画面　アイテムウィンドウ表示": "Customization screen　Item Window Display",
  "カスタマイズ画面　メニューウィンドウ　カーソル音": "Customization screen　Menu Window　Cursor Sound",
  "カスタマイズ画面　メニューウィンドウ　決定音": "Customization screen　Menu Window　Decision sound",
  "カスタマイズ画面　メニューウィンドウ表示": "Customization screen　Menu window display",
  "カムシン　アクチュエーター　中速　大きい動作等用　（足音でstop）": "Khamsin　Actuator Medium Speed　For loud movements ( stop at footsteps )",
  "カムシン　アクチュエーター　中速　短め（medを短く加工）": "Khamsin　Actuator Medium Speed　Short ( shortened med )",
  "カムシン　アクチュエーター　速": "Khamsin　Actuator Speed",
  "カムシン　アクチュエーター　遅　起き上がり時等用": "Khamsin　Actuator for slow rise etc.",
  "カムシン　アーマー　大　動作完了　動作開始時等": "Khamsin　Armor Major operation completed　When the operation starts",
  "カムシン　ジャンプ　着地": "Khamsin　Jump　Landing",
  "カムシン　ジャンプ　風切り": "Khamsin　Jump　Wind cutting",
  "カムシン　ダウン　中": "Khamsin　Down",
  "カムシン　ダウン　大": "Khamsin　Down Large",
  "カムシン　ミサイル　発射　単発（絨毯爆撃のため決め打ちの可能性あり）": "Khamsin　missile　firing　Single shot (possibly a deliberate shot due to carpet bombing )",
  "カムシン　ミサイル　着弾　単発": "Khamsin　missile　Impact　One-off",
  "カムシン　ムーブメント　中": "Khamsin　During the movement",
  "カムシン　ムーブメント　大": "Khamsin　Large movement",
  "カムシン　地面　踏みつけ": "Khamsin　ground　Trampling",
  "カムシン　打撃　振り　中": "Khamsin　Strike　Swinging",
  "カムシン　打撃　振り　小": "Khamsin　Strike　Small",
  "カムシン　斧　叩きつけ　中": "Khamsin Axe Slamming",
  "カムシン　斧　叩きつけ　大": "Khamsin Axe Slam Large",
  "カムシン　斧　振り　中": "Khamsin swinging axe",
  "カムシン　斧　振り　大": "Khamsin Axe Swinger",
  "カムシン　斧　掴む": "Khamsin grabs the axe",
  "カムシン　斧　構え風切り": "Kamshin Axe Wind Slash",
  "カムシン　死亡　電気": "Khamsin　death　electricity",
  "カムシン　滑り　停止　地面削れ": "Khamsin　Slip　Stop　Scrap the ground",
  "カムシン　足音　すり足": "Khamsin　footsteps　Sliding feet",
  "カムシン　足音　すり足　滑り停止時等（scuffの音量大にしたもの）": "Khamsin　footsteps　Sliding feet　When stopping a slide, etc. ( Scuff volume turned up )",
  "カムシン　足音　歩き": "Khamsin　footsteps　Walking",
  "カムシン　足音　歩き　小（体勢整える時等、walkの音量下げたもの）": "Khamsin　footsteps　Walking　Low ( lower the volume of the walk when adjusting your posture, etc. )",
  "カーソル移動音": "Cursor movement sound",
  "カーソル移動音 （オプション画面 BGMボリューム設定専用）": "Cursor movement sound ( Options screen (For BGM volume setting only )",
  "カーソル移動音 （オプション画面 ボイスボリューム設定専用）": "Cursor movement sound ( Options screen (For voice volume setting only )",
  "ガラス　落下": "Glass　Fall",
  "ガード　中": "Guarding",
  "ガードブレイク": "Guard Break",
  "キャンセル音": "Cancellation sound",
  "クナイで使用中　消したい": "Used with Kunai　I want to erase",
  "グラート　ガトリング　発射": "Grat　Gatling　firing",
  "グラート　キャノン　爆発": "Grat　Canon　explosion",
  "グラート　キャノン　発射": "Grat　Canon　firing",
  "グラート　キャノン　通過音": "Grat　Canon　Passing sound",
  "グラート　シールド　モーター音　中": "Grat　shield　Motor sound",
  "グラート　シールド　モーター音　小": "Grat　shield　Low motor noise",
  "グラート　シールド　動作音": "Grat　shield　Operation noise",
  "グラート　シールド　攻撃": "Grat　shield　attack",
  "グラート　シールドパンチ　風切り音　中": "Grat　Shield Punch　Wind noise medium",
  "グラート　シールドパンチ　風切り音　小": "Grat　Shield Punch　Low wind noise",
  "グラート　ダッシュ　風切り音": "Grat　dash　Wind noise",
  "グラート　ミサイル　爆発": "Grat　missile　explosion",
  "グラート　ミサイル　発射": "Grat　missile　firing",
  "グラート　ミサイル　通過音": "Grat　missile　Passing sound",
  "グラート　ミサイルハッチ 開く": "Grat　Missile hatch open",
  "グラート　ミサイルハッチ　閉じる": "Grat　Missile hatch　close",
  "グラート　ミサイルポッド　発射": "Grat　Missile Pod　firing",
  "グラート　ミサイルポッド　着弾": "Grat　Missile Pod　Impact",
  "グラート　ミサイルポッド　閉まる": "Grat　Missile Pod　Close",
  "グラート　ミサイルポッド　開く": "Grat　Missile Pod　open",
  "グラート　ローラー回転　中　開始": "Grat　Roller rotation start",
  "グラート　ローラー回転　小　停止": "Grat　Roller rotation stop",
  "グラート　ローラー回転　小　開始": "Grat　Roller rotation starts",
  "グラート　ローラー地面削り　停止": "Grat　Roller ground scraper　Stop",
  "グラート　叫び　大": "Grat　Scream loud",
  "グラート　叫び　小": "Grat　Scream Small",
  "グラート　回転蹴り　風切り": "Grat　Spin Kick　Wind cutting",
  "グラート　待機　アイドリング": "Grat　stand-by　Idling",
  "グラート　死亡スパーク": "Grat　Death Spark",
  "グラート　死亡爆発": "Grat　Death Explosion",
  "グラート　爆発予兆": "Grat　Premonition of an explosion",
  "グラート　稼働音　ノーマル": "Grat　Operation sound　normal",
  "グラート　稼働音　速": "Grat　Operating sound speed",
  "グラート　装甲　ダメージ音　": "Grat　Armor　Damage sound　",
  "グラート　装甲　動作　中": "Grat　Armor　In operation",
  "グラート　装甲　動作　大": "Grat　Armor　Large movement",
  "グラート　装甲　動作　小": "Grat　Armor　Small movement",
  "グラート　装甲　動作音　中": "Grat　Armor　During operation",
  "グラート　装甲　動作音　小": "Grat　Armor　Low operating noise",
  "グラート　装甲軋み音　中": "Grat　Armor creaking sound",
  "グラート　装甲軋み音　小": "Grat　Armor creaking noise",
  "グラート　足音　歩き": "Grat　footsteps　Walking",
  "グラート　足音　走り": "Grat　footsteps　Running",
  "グラート広場　環境音": "Grat Square　Ambient Sound",
  "グレネード": "Grenades",
  "グレーチング": "Grating",
  "ゲート　閉じる": "gate　close",
  "ゲート　閉まる": "gate　Close",
  "ゲート　開く": "gate　open",
  "ゲーム起動時１回だけ呼ばれる": "Called once when the game starts",
  "コナミ MG ビックリ音 （効果呼び出し）": "Konami MG surprise sound ( Effect call )",
  "コンクリート　壊れ　大": "concrete　Broken",
  "コンクリート　落下": "concrete　Fall",
  "コンテナ落下": "Container falls",
  "コンテナ落下風切り": "Container drop windbreak",
  "コンボ": "combo",
  "サイボーグ武器　雷電斬る": "Cyborg Weapons　Slash the Lightning",
  "サインアウトする(360専用)": "Sign out (360 only )",
  "サブ武器": "Secondary Weapon",
  "サブ武器　決定　大": "Secondary Weapon　Decision",
  "サミュエル　刀　地面ヒット": "Samuel hits the ground",
  "サム 刀　地面ヒット": "Sam Sword hits ground",
  "サム 衣擦れ 小": "Sam Rubbing clothes small",
  "サム　": "Sam　",
  "サム　QTE フィニッシュ": "Sam　QTE Finish",
  "サム　QTE　入り　ジャンプ　インパクト": "Sam　QTE　Enter　Jump　Impact",
  "サム　VR　納刀": "Sam　VR　Sheathing the sword",
  "サム　VR　納刀　鞘こすれ": "Sam　VR　Sheathing the sword　Scabbard Rubbing",
  "サム　すり足": "Sam　Sliding feet",
  "サム　ぴより": "Sam　Piyori",
  "サム　カウンター　投げ　風切り": "Sam　Counter Throw　Wind cutting",
  "サム　ガード": "Sam　guard",
  "サム　ガード受け止め声　中": "Sam　Guard catch voice",
  "サム　ガード受け止め声　小": "Sam　Guard catch voice low",
  "サム　キック　風切り": "Sam　kick　Wind cutting",
  "サム　サブ武器　投げる": "Sam　Secondary Weapon　throw",
  "サム　ジャンプ　風切り": "Sam　Jump　Wind cutting",
  "サム　スティーブン　押し合い　刀擦れ　1": "Sam　Steven　Pushing　Sword Rubbing　1",
  "サム　スティーブン　押し合い　刀擦れ　1　ストップ": "Sam　Steven　Pushing　Sword Rubbing　1　stop",
  "サム　スティーブン　押し合い　刀擦れ　2": "Sam　Steven　Pushing　Sword Rubbing　2",
  "サム　スティーブン　押し合い　刀擦れ　2　ストップ": "Sam　Steven　Pushing　Sword Rubbing　2　stop",
  "サム　スティーブン　押し合い　払いのけ　2回目": "Sam　Steven　Pushing　Dispel　Second time",
  "サム　スティーブン　斬りかかり1": "Sam　Steven Slash 1",
  "サム　スティーブン　斬りかかり2": "Sam　Steven Slash 2",
  "サム　スティーブンに斬りかかり時の溜め": "Sam　Steven attacks and time lags",
  "サム　スティーブンに斬りかかり時の溜め　ストップ": "Sam　Steven attacks and time lags　stop",
  "サム　タックルヒット": "Sam　Tackle hit",
  "サム　ダウン　中": "Sam　Down",
  "サム　ダウン　大": "Sam　Down Large",
  "サム　ダウン　小": "Sam　Down Small",
  "サム　ダッシュ時　納刀": "Sam　When dashing　Sheathing the sword",
  "サム　ダメージ声　中": "Sam　Damage sound",
  "サム　ダメージ声　大": "Sam　Damage loud",
  "サム　ダメージ声　小": "Sam　Damage voice low",
  "サム　パンチ　風切り": "Sam　punch　Wind cutting",
  "サム　フィニッシュ　納刀": "Sam　Finish　Sheathing the sword",
  "サム　ブレード　ソニックブーム ": "Sam　blade　Sonic Boom ",
  "サム　ヘリに衝突": "Sam　Collision with helicopter",
  "サム　ヘリ着地後　蹴りだし突進": "Sam　After the helicopter landed　Kick and rush",
  "サム　乱れ切り": "Sam　Random cut",
  "サム　刀 構え 握り カチャ": "Sam's sword Stance grip Katya",
  "サム　刀　ムーブメント": "Sam Katana Movement",
  "サム　刀　地面を削る": "Sam knife ground scraping",
  "サム　刀　地面を削る　ストップ": "Sam knife ground scraping　stop",
  "サム　刀　地面擦り": "Sam sword ground scraping",
  "サム　刀　地面擦り　ストップ": "Sam sword ground scraping　stop",
  "サム　刀　抜刀　衝撃波": "Sam's sword is drawn　shock wave",
  "サム　刀　振り　中": "Sam swinging his sword",
  "サム　刀　振り　大": "Sam Sword Swinger Large",
  "サム　刀　振り　小": "Sam Sword Swinger Small",
  "サム　刀　突き": "Sam's Sword Thrust",
  "サム　刀　落下": "Sam's sword falls",
  "サム　刀　風切り　払い": "Sam's Sword Wind Cutter　Payment",
  "サム　刀を鞘に入れ込む": "Sam　Put the sword into the sheath",
  "サム　刀地面叩きつけ": "Sam　Sword slamming",
  "サム　刀地面突き刺さり": "Sam　Sword pierced into the ground",
  "サム　刀振る　大": "Sam　Sword -wielding",
  "サム　刀振る　小": "Sam　Sword-wielding small",
  "サム　刀振る中": "Sam　While swinging a sword",
  "サム　刀突く": "Sam　pierce with a sword",
  "サム　刀飛ばされ": "Sam　Sword smashed",
  "サム　剣弾き音": "Sam　Sword flick sound",
  "サム　力を溜める": "Sam　Accumulate power",
  "サム　動作 風切り　ジャンプ": "Sam　Operation Wind cutting　Jump",
  "サム　動作　スライディング": "Sam　Operation　sliding",
  "サム　台詞　挑発": "Sam　lines　Taunt",
  "サム　回避声　中": "Sam　Evasion Voice",
  "サム　回避声　小": "Sam　Evasion Voice Low",
  "サム　地面滑り　中　": "Sam　Ground sliding",
  "サム　壁　ジャンプ": "Sam Wall Jump",
  "サム　壁　張り付き": "Sam Wall Mounted",
  "サム　壁着地": "Sam　Wall Landing",
  "サム　壁蹴り攻撃　インパクト": "Sam　Wall kick attack　Impact",
  "サム　奪　内蔵　抜き取り": "Built-in thumb snatcher　Extraction",
  "サム　奪　刀突き刺し": "Sam's Sword Stab",
  "サム　奪　刀風切り　（stab音量調整したもの）": "Sam's sword-snatching technique ( stab volume adjusted )",
  "サム　手をつく": "Sam　Put your hands together",
  "サム　手を着く": "Sam　Get your hands on",
  "サム　投げ飛ばされ　風切り": "Sam　Thrown away　Wind cutting",
  "サム　投げ飛ばされ後　ヘリ着地": "Sam　After being thrown　Helicopter Landing",
  "サム　攻撃掛け声　中": "Sam　Attack shout",
  "サム　攻撃掛け声　大": "Sam　Attack shout loud",
  "サム　攻撃掛け声　小": "Sam　Small attack shout",
  "サム　溜め　完了": "Sam　Accumulation　completion",
  "サム　溜め　斬撃モード　溜め持続音": "Sam　Accumulation　Slash Mode　Sustained sound",
  "サム　溜め　斬撃モード　溜め持続音　ストップ": "Sam　Accumulation　Slash Mode　Sustained sound　stop",
  "サム　溜め　斬撃モード時": "Sam　Accumulation　In slash mode",
  "サム　溜め　斬撃モード時　ストップ": "Sam　Accumulation　In slash mode　stop",
  "サム　溜め　通常時": "Sam　Accumulation　Normal",
  "サム　溜め　通常時 ストップ": "Sam　Accumulation　Normal stop",
  "サム　溜め切り　1": "Sam　Charge up　1",
  "サム　溜め切り　2": "Sam　Charge up　2",
  "サム　溜め切り　トリガーon　起爆": "Sam　Charge up　Trigger on　Detonation",
  "サム　溜め切り　衝撃波飛び": "Sam　Charge up　Shock wave jump",
  "サム　溜め切り　衝撃波飛び　キャンセル時　ストップ": "Sam　Charge up　Shock wave jump　When cancelling　stop",
  "サム　溜め切り　衝撃波飛び　壁ヒット　（効果埋め）": "Sam　Charge up　Shock wave jump　Wall hit ( effect fill )",
  "サム　溜め切り　（無数に刀振りエフェクトが出るもの等）": "Sam　Charged cut ( those that produce countless sword swing effects, etc. )",
  "サム　溜め斬り　演出": "Sam　Charge Slash　Direction",
  "サム　溜め突き　演出": "Sam　Charge Thrust　Direction",
  "サム　着地　中": "Sam　Landing",
  "サム　着地　大": "Sam　Landing large",
  "サム　着地　小": "Sam　Small landing",
  "サム　空中　ダッシュ　風切り": "Sam　air　dash　Wind cutting",
  "サム　衣擦れ 中": "Sam　Rubbing clothes Medium",
  "サム　衣擦れ　中": "Sam　Rubbing clothes",
  "サム　衣擦れ　大": "Sam　Clothes Rubbing",
  "サム　衣擦れ　小": "Sam　Clothes Rubbing Small",
  "サム　足音 歩く (属性)": "Sam　footsteps Walking ( attribute )",
  "サム　足音 走る (属性)": "Sam　footsteps Run ( attribute )",
  "サム　足音　擦り": "Sam　footsteps　Rubbing",
  "サム　足音　歩き": "Sam　footsteps　Walking",
  "サム　足音　走り": "Sam　footsteps　Running",
  "サム　蹴り　風切り": "Sam　Kick　Wind cutting",
  "サム　通常時　抜刀": "Sam　Normal　Draw your sword",
  "サム　通常時　納刀": "Sam　Normal　Sheathing the sword",
  "サム　通常時　納刀時　刀　風切り": "Sam　Normal　When sheathing the sword ,",
  "サム　鍔迫り合い": "Sam　group of close competitors",
  "サム　鍔迫り合い　ストップ": "Sam　group of close competitors　stop",
  "サム　雷電腕切られ時　挑発": "Sam　When Raiden's arm was cut off　Taunt",
  "サム　鞘　トリガーon": "Thumb sheath trigger on",
  "サム　鞘　ムーブメント": "Thumb Movement",
  "サム　鞘　取り付け": "Thumb sheath installation",
  "サム　鞘　取り外し": "Removing the thumb sheath",
  "サム　鞘　息を吹きかける": "Sam's sheath breathes",
  "サム　鞘　息吹きかけ": "Sam's sheath breath",
  "サム　鞘に刀を入れる　予兆": "Sam　Put the sword in the sheath　Omen",
  "サム　鞘トリガーon　起爆": "Sam　Scabbard trigger on　Detonation",
  "サムミュエル　ダッシュ地面削り　斬り　": "Samuel　Dash Ground Scraper　Slash　",
  "サム戦専用": "Sam Battle Exclusive",
  "サンダウナー シールドアーム　動作音　中": "Sundowner Shield Arm　During operation",
  "サンダウナー 足音 すり足": "Sundowner footsteps Sliding feet",
  "サンダウナー 足音　歩き": "Sundowner footsteps　Walking",
  "サンダウナー 足音　走り": "Sundowner footsteps　Running",
  "サンダウナー　コート衣擦れ　中": "Sundowner coat rubbing against each other",
  "サンダウナー　コート衣擦れ　小": "Sundowner coat, small wear",
  "サンダウナー　シールド　体ヒット　爆発": "Sundowner Shield　Body hit　explosion",
  "サンダウナー　シールド　刀ヒット　爆発": "Sundowner Shield　Sword hit　explosion",
  "サンダウナー　シールド　動作音　中": "Sundowner Shield　During operation",
  "サンダウナー　シールド　動作音　小": "Sundowner Shield　Low operating noise",
  "サンダウナー　シールド　構える": "Sundowner Shield　Get Ready",
  "サンダウナー　シールド　風切り": "Sundowner Shield　Wind cutting",
  "サンダウナー　シールドアーム　切断": "Sundowner Shield Arm　Disconnect",
  "サンダウナー　シールドアーム　動作音　小": "Sundowner Shield Arm　Low operating noise",
  "サンダウナー　シールド動作音　中": "Sundowner Shield operating sound",
  "サンダウナー　シールド動作音　大": "Sundowner Shield loud operation",
  "サンダウナー　シールド動作音　小": "Sundowner Shield - Low noise",
  "サンダウナー　シールド構え　解く": "Sundowner Shield Stance　solve",
  "サンダウナー　ダウン　中": "Sundowner down",
  "サンダウナー　ダウン　大": "Sundowner Down Large",
  "サンダウナー　ダウン　小": "Sundowner Down Small",
  "サンダウナー　バイザー閉じる": "Sundowner visor close",
  "サンダウナー　マチェット 風切り": "Sundowner Machete Wind cutting",
  "サンダウナー　マチェット　取り回し": "Sundowner Machete　Handling",
  "サンダウナー　マチェット　地面　ヒット": "Sundowner Machete　ground　hit",
  "サンダウナー　マチェット　斬る": "Sundowner Machete　kill",
  "サンダウナー　マチェット　風切り音　中": "Sundowner Machete　Wind noise medium",
  "サンダウナー　マチェット　風切り音　大": "Sundowner Machete　Loud wind noise",
  "サンダウナー　マチェット　風切り音　小": "Sundowner Machete　Low wind noise",
  "サンダウナー　剣がぶつかり合う": "Sundowner Swords Clash",
  "サンダウナー　地面滑り": "Sundowner ground slide",
  "サンダウナー　声　ガード　中": "Sundowner Voice Guard",
  "サンダウナー　声　ガード　大": "Sundowner Voice Guard Large",
  "サンダウナー　声　ダメージ　ガードブレイク": "Sundowner Voice Damage　Guard Break",
  "サンダウナー　声　ダメージ　中": "Sundowner Voice Damage",
  "サンダウナー　声　ダメージ　大": "Sundowner Voice Damage Large",
  "サンダウナー　声　ダメージ　小": "Sundowner Voice Damage Small",
  "サンダウナー　声　ダメージ　疲れ": "Sundowner Voice Damage　Fatigue",
  "サンダウナー　声　挑発": "Sundowner Voice Provocation",
  "サンダウナー　声　攻撃　大": "Sundowner: Large voice attack",
  "サンダウナー　声　溜め　短 ": "Sundowner Voice Short ",
  "サンダウナー　声　溜め　長": "Sundowner Voice Recording Long",
  "サンダウナー　声　移動　中": "Sundowner Voice Moving",
  "サンダウナー　声　移動　小": "Sundowner Voice Movement Small",
  "サンダウナー　攻撃声　中": "Sundowner attack sound",
  "サンダウナー　攻撃声　小": "Sundowner Attack Voice Low",
  "サンダウナー　攻撃用鉄塔　壊れ": "Sundowner attack tower　Broken",
  "サンダウナー　盾　サウンド　止める": "Sundowner Shield Sound　stop",
  "サンダウナー　盾閉じる　盾のぶつかり": "Sundowner Shield Close　Shield Clash",
  "サンダウナー　突進　雷電　競り合いヒット": "Sundowner Rush　Raiden　Competitive hit",
  "サンダウナー　突進　風切り": "Sundowner Rush　Wind cutting",
  "サンダウナー　衣擦れ　中": "Sundowner clothes rubbing together",
  "サンダウナー　衣擦れ　大": "Sundowner clothes chafing large",
  "サンダウナー　衣擦れ　小": "Sundowner clothing rub small",
  "サンダウナー　雷電　シールド　こじあけ": "Sundowner Raiden　shield　Pry open",
  "システム　ダイアログ　Mission Failed ミッション失敗 表示時": "system　dialog　Mission Failed When displayed",
  "システム　ダイアログ　Mission Failed ミッション失敗　非表示遷移時": "system　dialog　Mission Failed　When transitioning to hidden",
  "シャッター　閉まる": "The shutter closes",
  "シャッター　開く": "Shutter open",
  "ジャンプ着地": "Jump Landing",
  "ジャンプ跳ね上がり": "Jumping up",
  "スイカ　壊れ　中": "Watermelon　Broken",
  "スイカ　壊れ　大": "Watermelon　Broken",
  "スコア表示": "Score display",
  "スコア表示 ミス -100": "Score display Miss -100",
  "スティンガー": "Stinger",
  "スティンガー 通過音": "Stinger Passing sound",
  "スティンガー　構える": "Ready the Stinger",
  "スティンガー　構え下ろす": "Stinger lowered",
  "スティンガー　発射音": "Stinger firing sound",
  "スティンガー　着弾": "Stinger hits",
  "スティーブン　ガード": "Steven　guard",
  "スティーブン　シコ　インパクト": "Steven　Shiko　Impact",
  "スティーブン　シコ　動作と風切り": "Steven　Shiko　Movement and wind",
  "スティーブン　シコ〜マグネットパワーでヘリ持ち上げ": "Steven　Lifting the helicopter with magnetic power",
  "スティーブン　シコ後の咆哮　エネルギー解放": "Steven　Roar after shiko　Energy Release",
  "スティーブン　ジャイアントスイング　サムを投げ飛ばす": "Steven　Giant Swing　Throw Sam away",
  "スティーブン　ジャイアントスイング　サムを掴んで振り回す": "Steven　Giant Swing　Grab Sam and swing him around",
  "スティーブン　ジャンプ": "Steven　Jump",
  "スティーブン　ダウン　中": "Steven　Down",
  "スティーブン　ダウン　大": "Steven　Down Large",
  "スティーブン　ダウン　小": "Steven　Down Small",
  "スティーブン　パンチ　ヒット": "Steven　punch　hit",
  "スティーブン　ヘリ投げ　鉄板着地": "Steven　Helicopter Throw　An ironclad landing",
  "スティーブン　ヘリ投げ　風切り": "Steven　Helicopter Throw　Wind cutting",
  "スティーブン　力溜め　地面割れ": "Steven　Power Up　Ground crack",
  "スティーブン　地割れ攻撃": "Steven　Earth fissure attack",
  "スティーブン　掴み": "Steven　Grab",
  "スティーブン　攻撃　キック　振り　中": "Steven　attack　kick　Swinging",
  "スティーブン　攻撃　キック　振り　小": "Steven　attack　kick　Small",
  "スティーブン　攻撃　パンチ　振り　中": "Steven　attack　punch　Swinging",
  "スティーブン　攻撃　パンチ　振り　大": "Steven　attack　punch　Large swing",
  "スティーブン　攻撃　パンチ　振り　小": "Steven　attack　punch　Small",
  "スティーブン　攻撃　頭突き": "Steven　attack　Headbutt",
  "スティーブン　炎壁　消える": "Steven　Flame Wall　disappear",
  "スティーブン　炎壁　溶岩噴き出し": "Steven　Flame Wall　Lava spewing",
  "スティーブン　炎壁　開始": "Steven　Flame Wall　start",
  "スティーブン　着地　小": "Steven　Small landing",
  "スティーブン　衣擦れ　中": "Steven　Rubbing clothes",
  "スティーブン　衣擦れ　大": "Steven　Clothes Rubbing",
  "スティーブン　衣擦れ　小": "Steven　Clothes Rubbing Small",
  "スティーブン　衣擦れ　着地　中": "Steven　Rubbing clothes　Landing",
  "スティーブン　足音　すり足": "Steven　footsteps　Sliding feet",
  "スティーブン　足音　歩き": "Steven　footsteps　Walking",
  "スティーブン　足音　走り": "Steven　footsteps　Running",
  "スティーブン　追跡ラリアート時（難易度高ver時）　ソフト呼び": "Steven　Soft call during pursuit lariat (high difficulty version )",
  "スティーブン　鉄槌攻撃": "Steven　Hammer Attack",
  "スティーブン　長尺SE　ストップ": "Steven　Long SE　stop",
  "スティーブン地面殴り　地割れ": "Stephen hits the ground　Cracks in the ground",
  "スティーブン戦　開始直後のヘリ爆発　ヘリ投げ前のヘリ爆発": "Steven vs.　Helicopter explosion immediately after start　Helicopter explosion before the helicopter throw",
  "ステージ別　挑発": "By stage　Taunt",
  "ステージ別　歩き始め　台詞": "By stage　Start walking　lines",
  "ステージ移動　ふっ飛ばし攻撃時　風切り": "Stage movement　During a knockback attack　Wind cutting",
  "ステージ移動　吹っ飛ばされ着地時　風切り": "Stage movement　When blown away and landing　Wind cutting",
  "スパークを伴う金属ソリッド　壊れ　中": "Metallic solids with sparks　Broken",
  "スモークグレネード": "Smoke Grenade",
  "スライダー　ダメージ　中": "Slider Damage",
  "スライダー　ダメージ大": "Slider Damage Large",
  "スライダー　ミサイル　発射": "Slider Missile　firing",
  "スライダー　ミサイル　着弾": "Slider Missile　Impact",
  "スライダー　ミサイル　通過音": "Slider Missile　Passing sound",
  "スライダー　機銃　発射": "Slider machine gun　firing",
  "スライダー　死亡時　アイドリング　ボリュームダウン": "When Slider dies　Idling　Volume Down",
  "スライダー　死亡爆発": "Slider Death Explosion",
  "スライダー　死亡爆発　まとめて": "Slider Death Explosion　Collectively",
  "スローされるSEバス": "Thrown SE bus",
  "セントリーガン　発射": "Sentry Gun　firing",
  "ソファ　落下": "Sofa　Fall",
  "タイトル　決定音": "title　Decision sound",
  "タイトル画面　セーブ　カーソル音": "Title Screen　save　Cursor Sound",
  "タイトル画面　セーブ　決定音": "Title Screen　save　Decision sound",
  "ターゲットボード　出現": "Target Board　Appearance",
  "ターゲットボード　刀　斬る": "Target Board Sword Cut",
  "ダメージ編集　bm0130-013c": "DamageEdit　bm0130-013c",
  "ダンボール　動作音　中": "Cardboard　During operation",
  "ダンボール　動作音　小": "Cardboard　Low operating noise",
  "ダンボール　地面落ち　中": "Cardboard　Falling to the ground",
  "ダンボール　地面落ち　小": "Cardboard　Small ground drop",
  "チャフグレネード": "Chaff Grenade",
  "チャフグレネード　きらきら　止める": "Chaff Grenade　Sparkling　stop",
  "チャフグレネード　地面ヒット": "Chaff Grenade　Ground hit",
  "チャフグレネード　爆発": "Chaff Grenade　explosion",
  "デバッグ オシレータ信号": "debug Oscillator Signal",
  "デモ　兵士登場": "demo　Soldier appears",
  "デモ　兵士登場　兵士装備": "demo　Soldier appears　Soldier equipment",
  "ドラム缶": "Drum",
  "ドラム缶　オイル": "Drum　oil",
  "ドラム缶　倒れ": "Drum　Fall",
  "ドラム缶　倒れ&起き上がり　動作音": "Drum　Falling & getting up　Operation noise",
  "ドラム缶　動作　小": "Drum　Small movement",
  "ドラム缶　地面置く": "Drum　Place on the ground",
  "ドラム缶　転がり": "Drum　Rolling",
  "ドラム缶　転がり停止": "Drum　Rolling stop",
  "ナイフ　スラッシュ　ダメージ": "knife　Slash　damage",
  "ナイフ　抜刃": "knife　Blade removal",
  "ナイフ　握る": "knife　Grip",
  "ナイフ　構え": "knife　Stance",
  "ナイフ　突き": "knife　Thrust",
  "ナイフ　納刃": "knife　Sheathing the Blade",
  "ナビ表示": "Navigation display",
  "ハンマー　取り付け": "Hammer installation",
  "ハンマー　地面ヒット　大": "Hammer hits the ground hard",
  "ハンマー　地面ヒット　小": "Hammer Ground Hit Small",
  "ハンマー　地面擦り": "Hammer ground scraper",
  "ハンマー　攻撃　火花": "Hammer Attack　spark",
  "ハンマーヘッド　ボリューム調整": "Hammerhead　Volume adjustment",
  "バッテリーが黄色状態の時": "When the battery is yellow",
  "バトル スロー　ショート版　終了": "Battle Slow and short version　end",
  "バトル スロー　ショート版　開始 元当て身ズーム core_se_btl_knockoutblow": "Battle Slow and short version　start Original Attack Zoom core_se_btl_knockoutblow",
  "バトル　QTE　終了時　体力警告音　再開": "Battle　QTE　End Time　Health warning sound　Resume",
  "バトル　QTE　開始時　体力警告音一時停止": "Battle　QTE　Start time　Pause stamina warning sound",
  "バトル　エネルギー吸収終了": "Battle　Energy absorption ends",
  "バトル　エネルギー吸収開始": "Battle　Energy absorption begins",
  "バトル　スローモード終了": "Battle　Slow mode exit",
  "バトル　スローモード開始": "Battle　Start Slow Mode",
  "バトル　ブレードトリガー　終了　ソフト呼び出し 不要？": "Battle　Blade Trigger End　Soft Call Not needed ?",
  "バトル　ブレードトリガー　開始　ソフト呼び出し 不要？": "Battle　Blade Trigger Start　Soft Call Not needed ?",
  "バトル　リッパーモード終了": "Battle　Ripper mode exit",
  "バトル　リッパーモード開始": "Battle　Ripper mode started",
  "バトル　居合　ロックオン": "Battle　Iai　Lock On",
  "バトル　文字演出　奪　ソフト呼び出し": "Battle　Text production software call",
  "バトル　文字演出　奪　文字消える [ソフト呼び出し]": "Battle　Character effects : Characters disappear [ Soft call ]",
  "バトル　文字演出　奪　表示 [ソフト呼び出し]": "Battle　Text display [ Soft call ]",
  "バトル　文字演出　斬　ソフト呼び出し": "Battle　Text Production Zan Software Call",
  "バトル　文字演出　斬奪　[シーケンス呼び出し]": "Battle　Character production　Slash　[ Call sequence ]",
  "バトル　斬撃　斬奪可能箇所表示": "Battle　Slash　Display of possible slashing locations",
  "バトル　斬撃モード　終了　ソフト呼び出し": "Battle　Slash Mode　end　Soft Call",
  "バトル　斬撃モード　開始　ソフト呼び出し": "Battle　Slash Mode　start　Soft Call",
  "バトル　瀕死時　レッドアウト　終了": "Battle　When near death　Redout　end",
  "バトル　瀕死時　レッドアウト　開始": "Battle　When near death　Redout　start",
  "パイプ　落下　中": "pipe　Falling",
  "パイプ　落下　大": "pipe　Large fall",
  "パイプ　落下　小": "pipe　Small fall",
  "ヒット　キック": "hit　kick",
  "ヒット　パンチ": "hit　punch",
  "ヒット　プラ　中空": "hit　Plastic　Hollow",
  "ヒット　剣先擦る　コンクリート": "hit　Rubbing the tip of the sword　concrete",
  "ヒット　剣先擦る　土": "hit　Sword tip rubbed in clay",
  "ヒット　剣先擦る　金属": "hit　Rubbing the tip of the sword　metal",
  "ヒット　地面　強打": "hit　ground　Bang",
  "ヒット　木　固い": "Hit wood hard",
  "ヒット　果物　野菜": "hit　fruit　vegetables",
  "ヒット　金属　パイプ　小": "hit　metal　Small Pipe",
  "ヒット　金属　フェンス": "hit　metal　fence",
  "ヒット　金属　メタルギア": "hit　metal　Metal Gear",
  "ヒット　金属　中空": "hit　metal　Hollow",
  "ヒット　金属　固い": "hit　metal　Hard",
  "ヒット　金属　機械 メタルギア等": "hit　metal　machine Metal Gear etc.",
  "フィーチャーコンバットシステム　起動": "Feature Combat System　boot",
  "フェンス　落下　中": "fence　Falling",
  "フェンス　落下　小": "fence　Small fall",
  "フェーズジャンプでゲーム開始": "Phase jump to start the game",
  "フェーズ終了時　初期化": "At the end of the phase　Initialization",
  "フェーズ開始時　初期化": "At the start of the phase　Initialization",
  "フューチャーコンバットシステム ダメージエリアから出る": "Future Combat System Exit the damage area",
  "フューチャーコンバットシステム 破壊音": "Future Combat System Destruction Sound",
  "フューチャーコンバットシステム　ダメージ警告音": "Future Combat System　Damage warning sound",
  "フューチャーコンバットシステム　駆動音": "Future Combat System　Driving sound",
  "ブラン　ジェット突進　停止": "Bran　Jet Charge　Stop",
  "ブラン　ジェット突進　爆発": "Bran　Jet Charge　explosion",
  "ブラン　ジェット突進　開始": "Bran　Jet Charge　start",
  "ブラン　ダウン　中": "Bran　Down",
  "ブラン　ダウン　大": "Bran　Down Large",
  "ブラン　ダメージ　動作音　中": "Bran　damage　During operation",
  "ブラン　ダメージ　動作音　大": "Bran　damage　Operation noise is loud",
  "ブラン　ダメージ　動作音　小": "Bran　damage　Low operating noise",
  "ブラン　モーター音": "Bran　Motor sound",
  "ブラン　待機音": "Bran　Standby tone",
  "ブラン　歩き　水音": "Bran　Walking　Water Sound",
  "ブラン　死亡　爆発": "Bran　death　explosion",
  "ブラン　死亡スパーク": "Bran　Death Spark",
  "ブラン　滑り水切り音　中": "Bran　Slippery draining sound",
  "ブラン　滑り水切り音　大": "Bran　Slippery draining noise",
  "ブラン　滑り水切り音　小": "Bran　Low slippery drainage noise",
  "ブラン　滑り移動　ジェット音": "Bran　Sliding movement　Jet noise",
  "ブラン　火炎放射　ストップ　ソフト呼び": "Bran　Flamethrower　stop　Soft Call",
  "ブラン　火炎放射　発射": "Bran　Flamethrower　firing",
  "ブラン　火炎放射予兆": "Bran　Flame Thrower Premonition",
  "ブラン　火炎放射器　停止": "Bran　Flamethrower　Stop",
  "ブラン　火炎放射器　発射": "Bran　Flamethrower　firing",
  "ブラン　燃料タンク　爆発": "Bran　Fuel tank　explosion",
  "ブラン　燃料タンク破壊　火が噴き出す　loop": "Bran　Fuel tank destruction　Fire erupts　loop",
  "ブラン　稼働音　中速": "Bran　Operation sound　Medium speed",
  "ブラン　稼働音　速": "Bran　Operating sound speed",
  "ブラン　装甲　動作音　中": "Bran　Armor　During operation",
  "ブラン　装甲　動作音　小": "Bran　Armor　Low operating noise",
  "ブラン　足音　歩き": "Bran　footsteps　Walking",
  "ブラン　駆動音　中": "Bran　Driving sound",
  "ブレードウルフ　QTE　ジグザグジャンプ開始": "Blade Wolf　QTE　Start of Zigzag Jump",
  "ブレードウルフ　QTE　チェーンソーアイドリング": "Blade Wolf　QTE　Chainsaw idling",
  "ブレードウルフ　ジャンプ": "Blade Wolf　Jump",
  "ブレードウルフ　タックル": "Blade Wolf　Tackle",
  "ブレードウルフ　ダウン　中": "Blade Wolf　Down",
  "ブレードウルフ　ダウン　小": "Blade Wolf　Down Small",
  "ブレードウルフ　ダメージ声　中": "Blade Wolf　Damage sound",
  "ブレードウルフ　ダメージ声　大": "Blade Wolf　Damage loud",
  "ブレードウルフ　チェーンソー　HIT": "Blade Wolf　Chainsaw HIT",
  "ブレードウルフ　チェーンソー　HIT QTE": "Blade Wolf　Chainsaw HIT QTE",
  "ブレードウルフ　チェーンソー　アイドリング": "Blade Wolf　Chainsaw idling",
  "ブレードウルフ　チェーンソー　取り付け": "Blade Wolf　Chainsaw installation",
  "ブレードウルフ　チェーンソー　取り外し": "Blade Wolf　Chainsaw removal",
  "ブレードウルフ　チェーンソー　攻撃　振る": "Blade Wolf　Chainsaw Attack　shake",
  "ブレードウルフ　チェーンソー　攻撃　振る　大": "Blade Wolf　Chainsaw Attack　Shake large",
  "ブレードウルフ　チェーンソー地面破壊": "Blade Wolf　Chainsaw Ground Destruction",
  "ブレードウルフ　ナイフHIT ボディ": "Blade Wolf　Knife HIT body",
  "ブレードウルフ　ナイフHIT　コンクリート": "Blade Wolf　Knife HIT　concrete",
  "ブレードウルフ　ナイフ　取り外し": "Blade Wolf　knife　removal",
  "ブレードウルフ　ナイフ　投げ": "Blade Wolf　knife　Throw",
  "ブレードウルフ　ナイフ　通過音": "Blade Wolf　knife　Passing sound",
  "ブレードウルフ　ボイス　ストップ": "Blade Wolf　voice　stop",
  "ブレードウルフ　切断後　ダメージ＆移動": "Blade Wolf　After cutting　Damage & Movement",
  "ブレードウルフ　切断後　攻撃": "Blade Wolf　After cutting　attack",
  "ブレードウルフ　切断後移動　匍匐": "Blade Wolf　Move after cutting　creeping",
  "ブレードウルフ　台詞　QTE終り": "Blade Wolf　lines　QTE End",
  "ブレードウルフ　台詞　攻撃終り": "Blade Wolf　lines　Attack Ended",
  "ブレードウルフ　台詞　起き上がり": "Blade Wolf　lines　Getting up",
  "ブレードウルフ　台詞　首を持ち上げられる": "Blade Wolf　lines　Can lift neck",
  "ブレードウルフ　回復時　首振り": "Blade Wolf　During recovery　Shaking Head",
  "ブレードウルフ　尻尾　攻撃　振り　中": "Blade Wolf　tail　attack　Swinging",
  "ブレードウルフ　尻尾　攻撃　振り　小": "Blade Wolf　tail　attack　Small",
  "ブレードウルフ　攻撃声　中": "Blade Wolf　Attack sound",
  "ブレードウルフ　攻撃声　大": "Blade Wolf　Attack loud",
  "ブレードウルフ　死亡　叫び": "Blade Wolf　death　Scream",
  "ブレードウルフ　死亡　電気": "Blade Wolf　death　electricity",
  "ブレードウルフ　死亡爆発": "Blade Wolf　Death Explosion",
  "ブレードウルフ　気合い": "Blade Wolf　Spirit",
  "ブレードウルフ　爪　HIT": "Blade Wolf Claw HIT",
  "ブレードウルフ　爪　体当たり攻撃": "Blade Wolf Claw Body Slam Attack",
  "ブレードウルフ　爪　壁蹴り　地面蹴り": "Blade Wolf Claw Wall Kick　Ground kick",
  "ブレードウルフ　爪　壁蹴り　攻撃時": "Blade Wolf Claw Wall Kick　Attack",
  "ブレードウルフ　着地": "Blade Wolf　Landing",
  "ブレードウルフ　着地　大": "Blade Wolf　Landing large",
  "ブレードウルフ　破片　落下": "Blade Wolf　Debris　Fall",
  "ブレードウルフ　衣擦れ　中": "Blade Wolf　Rubbing clothes",
  "ブレードウルフ　衣擦れ　小": "Blade Wolf　Clothes Rubbing Small",
  "ブレードウルフ　装甲　破壊　中": "Blade Wolf　Armor　Destroying",
  "ブレードウルフ　足音　すり足": "Blade Wolf　footsteps　Sliding feet",
  "ブレードウルフ　足音　スライディング　停止": "Blade Wolf　footsteps　sliding　Stop",
  "ブレードウルフ　足音　スライディング　方向変換": "Blade Wolf　footsteps　sliding　Change of direction",
  "ブレードウルフ　足音　歩き": "Blade Wolf　footsteps　Walking",
  "ブレードウルフ　足音　歩き　一歩": "Blade Wolf　footsteps　Walking　One step",
  "ブレードウルフ　足音　走り": "Blade Wolf　footsteps　Running",
  "ブレードウルフ　足音　走り　一歩": "Blade Wolf　footsteps　Running　One step",
  "ブレードウルフ　遠吠え": "Blade Wolf　howling",
  "プラスチック　ホロウ　core_se_col_plastic_hollow_drop": "plastic　Hollow　core_se_col_plastic_hollow_drop",
  "プレイヤー　セントリーガン　発射": "Player Sentry Gun　firing",
  "プレイヤーボス武器　サンダウナー　鋏　": "Player Boss Weapons　Sundowner Scissors",
  "プレイヤーボス武器　サンダウナー　鋏　回転音止め": "Player Boss Weapons　Sundowner Scissor Rotation Sound Stopper",
  "プレイヤーボス武器　サンダウナー　鋏　振り　風切り　大": "Player Boss Weapons　Sundowner Scissors Swing　Large windbreaker",
  "プレイヤーボス武器　サンダウナー　鋏　振り　風切り　小": "Player Boss Weapons　Sundowner Scissors Swing　Small windbreaker",
  "プレイヤーボス武器　サンダウナー　鋏　振り風切り　中": "Player Boss Weapons　Sundowner, Scissors Swinging Wind",
  "プレイヤーボス武器　サンダウナー　鋏　構え風切り": "Player Boss Weapons　Sundowner Scissor-style Wind Slash",
  "プレイヤーボス武器　サンダウナー　鋏　肉斬る": "Player Boss Weapons　Sundowner Scissors Meat Slicer",
  "プレイヤーボス武器　モンスーン　釵 エネルギー　チャージ": "Player Boss Weapons　Monsoon Energy Charge",
  "プレイヤーボス武器　モンスーン　釵 壁ヒット": "Player Boss Weapons　Monsoon Wall Hit",
  "プレイヤーボス武器　モンスーン　釵　取り回し": "Player Boss Weapons　Monsoon Hair Styling",
  "プレイヤーボス武器　モンスーン　釵　手に戻ってくる　風切り": "Player Boss Weapons　Monsoon Hair Coming Back　Wind cutting",
  "プレイヤーボス武器　モンスーン　釵　投げる　風切り": "Player Boss Weapons　Monsoon Throw　Wind cutting",
  "プレイヤーボス武器　モンスーン　釵　振り　風切り　中": "Player Boss Weapons　Monsoon Hair Swing　During wind cutting",
  "プレイヤーボス武器　モンスーン　釵　振り　風切り　大": "Player Boss Weapons　Monsoon Hair Swing　Large windbreaker",
  "プレイヤーボス武器　モンスーン　釵　振り　風切り　小": "Player Boss Weapons　Monsoon Hair Swing　Small windbreaker",
  "プレイヤーボス武器　モンスーン　釵　掴み": "Player Boss Weapons　Monsoon Chopsticks",
  "プレーヤーのアクションボイス": "Player action voice",
  "ホテル出口　倒壊": "Hotel exit　collapse",
  "ホロチップ": "Holochip",
  "ボス武器　サンダウナー　ハサミ": "Boss Weapons　Sundowner Scissors",
  "ボス武器　ミストラル　槍": "Boss Weapons　Mistral Spear",
  "ボス武器　ミストラル　槍　取り回し": "Boss Weapons　Mistral Spear Handling",
  "ボス武器　ミストラル　鞭　取り回し": "Boss Weapons　Mistral Whip Handling",
  "ボス武器　ミストラル　鞭　地面ヒット": "Boss Weapons　Mistral Whip Ground Hit",
  "ボス武器　ミストラル　鞭　風切り　中": "Boss Weapons　Mistral Whip Wind Slash",
  "ボス武器　ミストラル　鞭　風切り　大": "Boss Weapons　Mistral Whip Large",
  "ボス武器　ミストラル　鞭　風切り　小": "Boss Weapons　Mistral Whip Wind Slash Small",
  "ボス武器　モンスーン　サイ": "Boss Weapons　monsoon　Rhino",
  "ボス武器　拳": "Boss Weapon Fist",
  "ボス武器　斧": "Boss Weapon Axe",
  "ボス武器　決定　サイ": "Boss Weapons　Decision　Rhino",
  "ボス武器　決定　サンダウナー": "Boss Weapons　Decision　Sundowner",
  "ボス武器　決定　鞭": "Boss Weapons　Decisive whip",
  "ボス武器　通常刀": "Boss Weapons　Normal sword",
  "マスチフ　アームガン 着弾": "Mastiff　Arm Gun Impact",
  "マスチフ　アームガン　発射": "Mastiff　Arm Gun　firing",
  "マスチフ　ガード中": "Mastiff　Guarding",
  "マスチフ　ジャンプ": "Mastiff　Jump",
  "マスチフ　ダウン中": "Mastiff　Down",
  "マスチフ　ダウン小": "Mastiff　Down Small",
  "マスチフ　ダメージ　中": "Mastiff　Damage in progress",
  "マスチフ　ダメージ声　小": "Mastiff　Damage voice low",
  "マスチフ　ドラミング": "Mastiff　drumming",
  "マスチフ　ハンマーパンチ振りかぶり": "Mastiff　Hammer Punch Swing",
  "マスチフ　ハンマーパンチ腕振り": "Mastiff　Hammer punch arm swing",
  "マスチフ　パンチコンボ腕振り": "Mastiff　Punch combo arm swing",
  "マスチフ　パンチ構え動作": "Mastiff　Punch preparation movement",
  "マスチフ　フック腕振り": "Mastiff　Hook arm swing",
  "マスチフ　動作音": "Mastiff　Operation noise",
  "マスチフ　呼吸音": "Mastiff　Breath sounds",
  "マスチフ　地面から手が抜けない": "Mastiff　I can't get my hands off the ground",
  "マスチフ　地面から手が抜ける": "Mastiff　Hands coming off the ground",
  "マスチフ　地面に手を突く": "Mastiff　Hand on the ground",
  "マスチフ　地面叩きつけられ": "Mastiff　Slammed to the ground",
  "マスチフ　地面破壊音 中": "Mastiff　Ground breaking sound Medium",
  "マスチフ　地面破壊音小": "Mastiff　Small ground destruction sound",
  "マスチフ　手が抜けない": "Mastiff　I can't let my guard down",
  "マスチフ　投げられ　風切り": "Mastiff　Thrown　Wind cutting",
  "マスチフ　掴み": "Mastiff　Grab",
  "マスチフ　攻撃声　中": "Mastiff　Attack sound",
  "マスチフ　攻撃声　大": "Mastiff　Attack loud",
  "マスチフ　攻撃声　小": "Mastiff　Attack voice low",
  "マスチフ　歩き": "Mastiff　Walking",
  "マスチフ　死亡": "Mastiff　death",
  "マスチフ　死亡スパーク": "Mastiff　Death Spark",
  "マスチフ　死亡爆発": "Mastiff　Death Explosion",
  "マスチフ　着地": "Mastiff　Landing",
  "マスチフ　締め上げ　中": "Mastiff　Tightening up",
  "マスチフ　締め上げ　大": "Mastiff　Tightening Large",
  "マスチフ　蒸気噴出": "Mastiff　Steam eruptions",
  "マスチフ　衣擦れ　大": "Mastiff　Clothes Rubbing",
  "マスチフ　衣擦れ中": "Mastiff　Rubbing clothes",
  "マスチフ　衣擦れ小": "Mastiff　Clothes Rubbing Small",
  "マスチフ　走り": "Mastiff　Running",
  "マスチフ　足音　すり足": "Mastiff　footsteps　Sliding feet",
  "マスチフ　足音　小": "Mastiff　Small footsteps",
  "マスチフ　馬乗り": "Mastiff　Horse riding",
  "マスティフ　破片爆発　血　小": "Mastiff　Shrapnel Explosion Blood Small",
  "マチェット振り　中": "Swinging a machete",
  "マチェット振り　大": "Machete Swing Large",
  "マチェット振り　小": "Machete Swing Small",
  "マップ表示": "Map display",
  "ミサイル　地面あ突き刺さり": "missile　Pierced into the ground",
  "ミサイル　爆発": "missile　explosion",
  "ミサイル　発射": "missile　firing",
  "ミサイル　通過": "missile　Passing",
  "ミストラル　qte　槍突き刺し": "Mistral　Qte　Spear thrust",
  "ミストラル　よろめき声": "Mistral　Stumbling voice",
  "ミストラル　ガード声　中": "Mistral　Guard Voice",
  "ミストラル　ガード声　大": "Mistral　Guard loud",
  "ミストラル　ガード声　小": "Mistral　Guard Voice Low",
  "ミストラル　ジャンプ風切り": "Mistral　Jump Wind Slash",
  "ミストラル　ダウン　中": "Mistral　Down",
  "ミストラル　ダウン　大": "Mistral　Down Large",
  "ミストラル　ダウン　小": "Mistral　Down Small",
  "ミストラル　ダメージ声　中": "Mistral　Damage sound",
  "ミストラル　ダメージ声　大": "Mistral　Damage loud",
  "ミストラル　ダメージ声　小": "Mistral　Damage voice low",
  "ミストラル　ナイフ　取りはずし": "Mistral　knife　Removal",
  "ミストラル　ナイフ　取り付け": "Mistral　knife　attachment",
  "ミストラル　ナイフ　攻撃": "Mistral　knife　attack",
  "ミストラル　ナイフ　攻撃　中": "Mistral　knife　Under attack",
  "ミストラル　仔月光 取り付け": "Mistral　Baby Moonlight attachment",
  "ミストラル　仔月光　腕取り外し": "Mistral　Baby Moonlight　Arm removal",
  "ミストラル　仔月光投げ　通過音": "Mistral　Baby Moonlight Thrower　Passing sound",
  "ミストラル　仔月光腕もぎ　投げ　風切り": "Mistral　Baby Moonlight Arm Pick　Throw　Wind cutting",
  "ミストラル　全方位攻撃": "Mistral　All-direction attack",
  "ミストラル　動作声　小": "Mistral　Low volume",
  "ミストラル　台詞　qte 鞭　終了時": "Mistral　lines　Qte When the whip ends",
  "ミストラル　台詞　ステージ2へ移動　失敗": "Mistral　Failed to move to dialogue stage 2",
  "ミストラル　台詞　ステージ2へ移動　成功": "Mistral　Move to dialogue stage 2 successfully",
  "ミストラル　台詞　仔月光　投げる": "Mistral　lines　Baby Moonlight　throw",
  "ミストラル　台詞　仔月光　投げる予兆": "Mistral　lines　Baby Moonlight　Premonition of throwing",
  "ミストラル　台詞　最後の攻撃": "Mistral　lines　Final Attack",
  "ミストラル　台詞　武器再生": "Mistral　lines　Weapon Regeneration",
  "ミストラル　回避": "Mistral　Avoid",
  "ミストラル　地面に手を突く": "Mistral　Hand on the ground",
  "ミストラル　声　ガードブレイク　やられ": "Mistral Voice Guard Break　Defeated",
  "ミストラル　攻撃　鞭地面這わせ": "Mistral　attack　Whip on the ground",
  "ミストラル　攻撃声　中": "Mistral　Attack sound",
  "ミストラル　攻撃声　大": "Mistral　Attack loud",
  "ミストラル　攻撃声　小": "Mistral　Attack voice low",
  "ミストラル　槍　地面叩きつけ": "Mistral Spear Ground Slam",
  "ミストラル　槍　振り音": "Mistral spear swing sound",
  "ミストラル　槍　攻撃　中": "Mistral spear attacking",
  "ミストラル　槍　攻撃　大": "Mistral Spear Attack Large",
  "ミストラル　槍　攻撃　小": "Mistral Spear Small Attack",
  "ミストラル　槍　斬り音": "Mistral spear slash sound",
  "ミストラル　死亡爆発": "Mistral　Death Explosion",
  "ミストラル　着地": "Mistral　Landing",
  "ミストラル　移動　スライド": "Mistral　Move　slide",
  "ミストラル　移動　スライド　開始": "Mistral　Move　slide　start",
  "ミストラル　笑い声": "Mistral　laughter",
  "ミストラル　衣擦れ　中": "Mistral　Rubbing clothes",
  "ミストラル　衣擦れ　大": "Mistral　Clothes Rubbing",
  "ミストラル　衣擦れ　小": "Mistral　Clothes Rubbing Small",
  "ミストラル　足音　すり足": "Mistral　footsteps　Sliding feet",
  "ミストラル　足音　歩き": "Mistral　footsteps　Walking",
  "ミストラル　足音　走り": "Mistral　footsteps　Running",
  "ミストラル　足音（コンクリート）切り替え": "Mistral　Footsteps (concrete) toggle",
  "ミストラル　雑魚用　台詞　ストップ": "Mistral　For small fry　lines　stop",
  "ミストラル　鞭　ヒット": "Mistral Whip Hit",
  "ミストラル　鞭　地面叩きつけ": "Mistral Whip Ground Slam",
  "ミストラル　鞭　振り音": "Mistral Whip Sound",
  "ミストラル　鞭　攻撃　中": "Mistral Whip Attack",
  "ミストラル戦　石油プラント": "Mistral Battle　Oil Plant",
  "ミッション内容表示": "Mission Details Display",
  "ムービーに埋め込んだら消すこと": "Once embedded in the movie, delete it",
  "ムービー経由でゲーム開始": "Start the game via a movie",
  "メイン武器　木刀　決定": "Primary Weapon　Wooden sword　Decision",
  "メイン武器　決定　中": "Primary Weapon　To be decided",
  "メイン武器　決定　大": "Primary Weapon　Decision",
  "メニューに入る": "Enter the menu",
  "メニューを抜ける": "Exit the menu",
  "モバイルｐｃステーション 解除": "Mobile PC Station Cancellation",
  "モンスーン　サイ　ヒット　刀": "monsoon　Rhino　Hit Sword",
  "モンスーン　ジャンプ　大": "monsoon　Jump Large",
  "モンスーン　ジャンプ　風切り": "monsoon　Jump　Wind cutting",
  "モンスーン　スモークグレネード　つかむ": "monsoon　Smoke Grenade　Grab",
  "モンスーン　スモークグレネード　投げる": "monsoon　Smoke Grenade　throw",
  "モンスーン　スモークグレネード　爆発": "monsoon　Smoke Grenade　explosion",
  "モンスーン　ダウン　中": "monsoon　Down",
  "モンスーン　ダウン　大": "monsoon　Down Large",
  "モンスーン　ダウン　小": "monsoon　Down Small",
  "モンスーン　バレット　発射": "monsoon　Barret　firing",
  "モンスーン　バレット攻撃　開始": "monsoon　Bullet Attack　start",
  "モンスーン　体発射　ヒット音": "monsoon　Body Launch　Hit sound",
  "モンスーン　体発射　通過音": "monsoon　Body Launch　Passing sound",
  "モンスーン　全身ダイナミック　戻り": "monsoon　Full body dynamic　return",
  "モンスーン　全身分裂": "monsoon　Whole body division",
  "モンスーン　分裂　キック": "monsoon　division　kick",
  "モンスーン　地面に手を突く": "monsoon　Hand on the ground",
  "モンスーン　声　オブジェ投げ　開始": "Monsoon Voice Object Throwing　start",
  "モンスーン　声　オブジェ投げる": "Monsoon Voice Object Throwing",
  "モンスーン　声　ダメージ　ガードブレイク": "Monsoon Voice Damage　Guard Break",
  "モンスーン　声　ダメージ　中": "Monsoon Voice Damage",
  "モンスーン　声　ダメージ　大": "Monsoon Voice Damage : Large",
  "モンスーン　声　ダメージ　小": "Monsoon Voice Damage Small",
  "モンスーン　声　ダメージ　疲れ": "Monsoon Voice Damage　Fatigue",
  "モンスーン　声　分裂　挑発": "Monsoon Voice Split　Taunt",
  "モンスーン　声　動作　小": "Monsoon voice action small",
  "モンスーン　声　回避": "Avoid the monsoon noise",
  "モンスーン　声　攻撃　中": "Monsoon Voice Attack",
  "モンスーン　声　攻撃　台": "Monsoon Voice Attack Unit",
  "モンスーン　声　攻撃　小": "Monsoon Voice Attack Small",
  "モンスーン　声　攻撃　投げる": "Monsoon Voice Attack　throw",
  "モンスーン　声　攻撃　溜める　短": "Monsoon Voice Attack　Accumulate short",
  "モンスーン　声　攻撃　溜める　長": "Monsoon Voice Attack　Accumulation length",
  "モンスーン　声　攻撃ノックバック回復": "Monsoon Voice Attack Knockback Recovery",
  "モンスーン　声　早い起き上がり": "Monsoon voice early rise",
  "モンスーン　攻撃　分離　突進": "monsoon　attack　Separation　Charge",
  "モンスーン　攻撃オブジェ": "monsoon　Attack Object",
  "モンスーン　死亡爆発": "monsoon　Death Explosion",
  "モンスーン　着地　中": "monsoon　Landing",
  "モンスーン　着地　小": "monsoon　Small landing",
  "モンスーン　衣擦れ　中": "monsoon　Rubbing clothes",
  "モンスーン　衣擦れ　大": "monsoon　Clothes Rubbing",
  "モンスーン　衣擦れ　小": "monsoon　Clothes Rubbing Small",
  "モンスーン　足音　すり足": "monsoon　footsteps　Sliding feet",
  "モンスーン　足音　歩き": "monsoon　footsteps　Walking",
  "モンスーン　足音　走り": "monsoon　footsteps　Running",
  "モンスーン　蹴り　風切り　中": "monsoon　Kick　During wind cutting",
  "モンスーン　蹴り　風切り　大": "monsoon　Kick　Large windbreaker",
  "モンスーン　釵　つかむ": "Monsoon",
  "モンスーン　釵　ハンドリング": "Monsoon Sai Handling",
  "モンスーン　釵　風切り　中": "Monsoon hairpin cutting",
  "モンスーン　釵　風切り　大": "Monsoon Hairpin Large",
  "モンスーン　釵　風切り　小": "Monsoon Hairpin Small",
  "モンスーン　雑魚用　台詞　止める": "monsoon　For small fry　lines　stop",
  "モンスーン　電磁パワー　発動": "monsoon　Electromagnetic power activation",
  "モンスーン　顔面　スラッシュ": "monsoon　face　Slash",
  "モンスーン戦　装甲車　激突": "Monsoon Battle　Armored vehicles　Clash",
  "ヨーヨー　燃え": "Yo-yo burning",
  "ライオットシールド　ガード音": "Riot Shield　Guard Sound",
  "ライオットシールド　破壊": "Riot Shield　destruction",
  "ラプター　ぴより　スパーク": "Raptor Piyori　spark",
  "ラプター　ぴより　スパーク　ストップ": "Raptor Piyori　spark　stop",
  "ラプター　アーマー揺れ　中": "Raptor Armor Shaking",
  "ラプター　アーマー揺れ　小": "Raptor Armor Shake Small",
  "ラプター　エンジン音": "Raptor engine sound",
  "ラプター　エンジン音　止める": "Raptor engine sound　stop",
  "ラプター　ジャンプ": "Raptor Jump",
  "ラプター　ステップ": "Raptor Step",
  "ラプター　ダウン中": "Raptor Down",
  "ラプター　ダウン小": "Raptor Down Small",
  "ラプター　ダメージぴより声": "Raptor Damage Piyo Voice",
  "ラプター　ダメージアーマー揺れ　中": "Raptor Damage Armor Shaking",
  "ラプター　ダメージアーマー揺れ　小": "Raptor Damage Armor Shake Small",
  "ラプター　ダメージ声　中": "Raptor Damage Voice",
  "ラプター　ダメージ声　小": "Raptor Damage Voice Small",
  "ラプター　仔月光　乗り込み": "Raptor Baby Gekko　Boarding",
  "ラプター　仔月光　飛び出し": "Raptor Baby Gekko　Jumping out",
  "ラプター　動作時声　小": "Raptor operation sound is low",
  "ラプター　動作音　中": "Raptor in motion",
  "ラプター　動作音　小": "Raptor quiet operation",
  "ラプター　叫び　痺れ": "Raptor Cry　numbness",
  "ラプター　叫び声　中　": "Raptor screaming",
  "ラプター　叫び声　小": "Raptor Shout Small",
  "ラプター　唸り声　待機中": "Raptor Growl　Waiting",
  "ラプター　唸り声　止める": "Raptor Growl　stop",
  "ラプター　回転蹴り": "Raptor Spin Kick",
  "ラプター　威嚇声": "Raptor 's Threat",
  "ラプター　死亡スパーク": "Raptor Death Spark",
  "ラプター　死亡叫び": "Raptor Death Cry",
  "ラプター　死亡爆発": "Raptor Death Explosion",
  "ラプター　着地": "Raptor Landing",
  "ラプター　稼働音　中速": "Raptor operation sound　Medium speed",
  "ラプター　稼働音　速": "Raptor Operational Speed of Sound",
  "ラプター　起動音": "Raptor startup sound",
  "ラプター　足音　歩き": "Raptor footsteps　Walking",
  "ラプター　足音　走り": "Raptor footsteps　Running",
  "ラプター　踵の剣　収納": "Raptor Heel Sword　Storage",
  "ラプター　踵の剣　展開": "Raptor Heel Sword　Expand",
  "ラプター　蹴り": "Raptor Kick",
  "ラプター　首振り攻撃": "Raptor Head Swing Attack",
  "ラプター用EMPジェネレーター 爆発大": "Raptor EMP Generator Big explosion",
  "ラプター用EMPジェネレーター　チャージ": "Raptor EMP Generator Charge",
  "ラプター用EMPジェネレーター　消滅": "Raptor EMP generator destroyed",
  "ラプター用EMPジェネレーター　爆発": "Raptor EMP generator explosion",
  "ラプター用EMPジェネレーター　発射": "Raptor EMP generator firing",
  "ラプター用EMPジェネレーター　通過音": "Raptor EMP generator passing sound",
  "ラプター用ＭＫ19改　発射": "19 modified launcher for Raptor",
  "ラプター用ＭＫ19改　着弾": "19 modified for Raptor",
  "ラプター用ＭＫ19改　通過音": "Raptor MK 19 modified passing sound",
  "リザルト表示": "Result display",
  "リトライでゲーム開始": "Retry and start the game",
  "リトライでゲーム開始 SE実装あり": "Retry and start the game With SE implementation",
  "レイ　二戦目　登場一連": "Ray　Second match　Appearances",
  "レイ　体斬られ": "Ray　Body slashed",
  "レイ　体斬られ終り": "Ray　Body slashed to death",
  "レイ　切断後　ダウン音": "Ray　After cutting　Down sound",
  "レイ　待機中　唸り声": "Ray　Waiting　Growl",
  "レイ　真っ二つ": "Ray　Split in two",
  "レイ　背中　突きさされ": "Ray　back　Pierced",
  "レイ　腕切断": "Ray　Arm amputation",
  "レイ戦 塔から駆け下りる": "Ray Battle Run down from the tower",
  "レイ戦　レイ噛みつき〜投げ飛ばされ": "Ray Battle　Ray gets bitten and thrown away",
  "レイ戦　剣取り飛ばし〜着地": "Ray Battle　Sword grabbing ~ Landing",
  "レイ戦　剣掴み〜レイ噛みつき": "Ray Battle　Sword grab ~ Ray bites",
  "レイ戦　塔叩きつけられ": "Ray Battle　Tower slammed",
  "レイ戦　腕斬り落とし": "Ray Battle　Arm cut off",
  "レイ戦　腕斬り落とし　振りかぶり": "Ray Battle　Arm cut off　Swinging",
  "レールガン　エネルギーチャージ": "Railgun　Energy Charge",
  "レールガン　オーバーヒート ": "Railgun　overheat ",
  "下水": "sewage",
  "不要？": "Not needed ?",
  "仔月光": "Baby Moonlight",
  "仔月光 pA40登場 　暗闇で目が光る笑い声（効果貼付）": "Baby Moonlight pA40 appears 　Glowing eyes in the dark (with effects )",
  "仔月光 pA40登場 石炭の中からジャンプ　（効果貼付）": "Baby Moonlight pA40 appears Jump from the coal ( with effect )",
  "仔月光 おびえる声": "Baby Moonlight Frightened voice",
  "仔月光 ダウン　中": "Baby Moonlight Down",
  "仔月光 ダメージ声": "Baby Moonlight Damage voice",
  "仔月光 プレイアブル　死亡電気": "Baby Moonlight Playable　Death Electricity",
  "仔月光 刀 斬られ": "Baby Moonlight sword Slashed",
  "仔月光 叫び声": "Baby Moonlight Scream",
  "仔月光 手　地面接地音": "Baby Moonlight Hand- ground contact sound",
  "仔月光 振りほどく": "Baby Moonlight Shake it off",
  "仔月光 攻撃　掛け声": "Baby Moonlight attack　shout",
  "仔月光 死亡　叫び": "Baby Moonlight death　Scream",
  "仔月光 疑問　声": "Baby Moonlight Questions",
  "仔月光 発見　声": "Baby Moonlight Discovery Voice",
  "仔月光 笑い声": "Baby Moonlight laughter",
  "仔月光　ジャンプ": "Baby Moonlight　Jump",
  "仔月光　スタンガン　ヒット": "Baby Moonlight　stun gun　hit",
  "仔月光　スモークグレネード　リアクション": "Baby Moonlight　Smoke Grenade　reaction",
  "仔月光　ダウン　小": "Baby Moonlight　Down Small",
  "仔月光　バッティングトス　掛け声": "Baby Moonlight　Batting Toss　shout",
  "仔月光　バット　スイング掛け声": "Baby Moonlight　bat　Swing shout",
  "仔月光　バット殴られ": "Baby Moonlight　Hit with a bat",
  "仔月光　プレイアブル  死亡爆発": "Baby Moonlight　Playable  Death Explosion",
  "仔月光　ミストラルに投げられ": "Baby Moonlight　Thrown into the Mistral",
  "仔月光　レーザーアーム　閉じる": "Baby Moonlight　Laser Arm　close",
  "仔月光　レーザーアーム　開く": "Baby Moonlight　Laser Arm　open",
  "仔月光　仔月光を取りだし": "Baby Moonlight　Take out the baby moonlight",
  "仔月光　声　やじ　": "Little Moon Light Voice Heckler　",
  "仔月光　手をつかむ": "Baby Moonlight　Grab your hand",
  "仔月光　挑発": "Baby Moonlight　Taunt",
  "仔月光　槍生成": "Baby Moonlight　Spear Creation",
  "仔月光　死亡スパーク　ストップ": "Baby Moonlight　Death Spark　stop",
  "仔月光　死亡爆発": "Baby Moonlight　Death Explosion",
  "仔月光　死亡電気": "Baby Moonlight　Death Electricity",
  "仔月光　白刃どり": "Baby Moonlight　White blade cutting",
  "仔月光　着地": "Baby Moonlight　Landing",
  "仔月光　稼働音　中": "Baby Moonlight　Operating sound",
  "仔月光　稼働音　速": "Baby Moonlight　Operating sound speed",
  "仔月光　腕取り外し": "Baby Moonlight　Arm removal",
  "仔月光　腕振り　中": "Baby Moonlight　Swinging arms",
  "仔月光　腕振り　小": "Baby Moonlight　Small arm swing",
  "仔月光　腕筋肉　動作音　中": "Baby Moonlight　Arm muscles　During operation",
  "仔月光　腕筋肉　動作音　小": "Baby Moonlight　Arm muscles　Low operating noise",
  "仔月光　足音　歩き": "Baby Moonlight　footsteps　Walking",
  "仔月光　足音　走り": "Baby Moonlight　footsteps　Running",
  "仔月光　転がり　移動音": "Baby Moonlight　Rolling　Movement sound",
  "仔月光人間　2体が分離する　（ソフト呼び）": "Baby Moonlight Human　The two bodies separate ( soft call )",
  "任意無線　メニュー　入る": "Any Radio　Menu",
  "任意無線　メニュー　出る": "Any Radio　Menu appears",
  "任意無線からカスタマイズやVRへ移動する際に音を止める": "Stops sound when moving from any radio to customization or VR",
  "保険": "insurance",
  "兵士　はいずり": "soldier　Crawling",
  "兵士　グレネード　投げる": "soldier　Grenades　throw",
  "兵士　グレネード投げる": "soldier　Throw a Grenade",
  "兵士　パルス死亡爆発": "soldier　Pulse Death Explosion",
  "兵士　体燃える": "soldier　Body burning",
  "兵士　体燃える 止まる": "soldier　Body burning Stop",
  "兵士　倒れる　中": "soldier　While collapsing",
  "兵士　倒れる　小": "soldier　Falling small",
  "兵士　叫び　燃え時": "soldier　Scream　Burning Time",
  "兵士　台詞　": "soldier　lines　",
  "兵士　台詞　攻撃時": "soldier　lines　Attack",
  "兵士　声　ぴより　ふらつき": "Soldier Voice Piyori　Lightheadedness",
  "兵士　声　ぴより　ふらつき戻る": "Soldier Voice Piyori　Wobbling back",
  "兵士　声　切断後　動作": "After the soldier's voice was cut off　Operation",
  "兵士　声　切断後　攻撃": "After the soldier's voice was cut off　attack",
  "兵士　怯え声": "soldier　Frightened voice",
  "兵士　手をつく": "soldier　Put your hands together",
  "兵士　死亡前　電気走る": "soldier　Before death　Electric run",
  "兵士　破片大　消滅": "soldier　Large debris　Disappearance",
  "兵士　破片大　消滅 煙": "soldier　Large debris　Disappearance smoke",
  "兵士　肉片　落下": "soldier　Meat　Fall",
  "兵士　膝をつく": "soldier　Kneel",
  "兵士　衣擦れ　中": "soldier　Rubbing clothes",
  "兵士　衣擦れ　小": "soldier　Clothes Rubbing Small",
  "兵士　装備　中": "soldier　Equipped",
  "兵士　装備　小": "soldier　Equipment Small",
  "兵士　足音　すり足": "soldier　footsteps　Sliding feet",
  "兵士　足音　歩き": "soldier　footsteps　Walking",
  "兵士　足音　走り": "soldier　footsteps　Running",
  "兵士　電気 痺れ": "soldier　electricity numbness",
  "兵士　電気 痺れ ストップ": "soldier　electricity numbness stop",
  "兵士　飛び降り": "soldier　Jumping",
  "兵士ガード声　中": "Soldier Guard Voice",
  "兵士ガード声　小": "Soldier Guard Low Voice",
  "兵士タイプa": "Soldier Type A",
  "兵士タイプb ": "Soldier type B ",
  "兵士タイプd": "Soldier Type D",
  "兵士タイプe": "Soldier Type E",
  "兵士タイプｃ": "Soldier Type C",
  "兵士ダメージ声　中": "Soldier Damage Voice",
  "兵士ダメージ声　大": "Soldier Damage Loud",
  "兵士ダメージ声　小": "Soldier Damage Voice Small",
  "兵士動作声　小": "Soldier movement voice small",
  "兵士攻撃声　中": "Soldier attack sound",
  "兵士攻撃声　大": "Soldier attack loud",
  "兵士攻撃声　小": "Soldier attack voice low",
  "兵士死亡声　静か": "Soldier death announcement　quiet",
  "刀 切る 機械": "sword Cut machine",
  "刀 切る （木+パイプS） ベンチや屋台など": "sword Cut ( Wood + Pipe S ) Benches and stalls etc.",
  "刀 切る （木　中空）": "sword Cut ( Hollow tree )",
  "刀 切る （木）": "sword Cut (tree)",
  "刀 切る （木）　小": "sword Cut (Thu) Small",
  "刀 切る （肉体）": "sword Cut ( body )",
  "刀 切る （金属中空+パイプS） 屋台など": "sword Cut ( Hollow metal + pipe S ) Food stalls, etc.",
  "刀 切る　コンクリート": "sword Cut　concrete",
  "刀 切る　コンクリート+屋根": "sword Cut　Concrete + Roof",
  "刀 切る　ソファ": "sword Cut　Sofa",
  "刀 切る　パイプ　中": "sword Cut　In the pipe",
  "刀 切る　パイプ　小": "sword Cut　Small Pipe",
  "刀 切る　フェンス": "sword Cut　fence",
  "刀 切る　プラスチック": "sword Cut　plastic",
  "刀 切る　土のう": "sword Cut　Sandbags",
  "刀 切る　木　大": "sword Cutting wood Large",
  "刀 切る　果物": "sword Cut　fruit",
  "刀 切る　段ボール": "sword Cut　cardboard",
  "刀 切る　草": "sword Cutting Grass",
  "刀 切る　金属　中空": "sword Cut　metal　Hollow",
  "刀 切る　金属　中空　大": "sword Cut　metal　Hollow Large",
  "刀 切る　金属　中空　小": "sword Cut　metal　Hollow Small",
  "刀 切る　金属　小": "sword Cut　Small metal",
  "刀 切る　鉢": "sword Cutting bowl",
  "刀 切れないヒット音 （属性）": "sword Uninterrupted hit sound ( attribute )",
  "刀 抜刀": "sword Draw your sword",
  "刀 振る 中": "sword shake Medium",
  "刀 振る 大": "sword shake large",
  "刀 振る 小": "sword shake small",
  "刀 握りしめる": "sword Clench",
  "刀 斬る （金属）": "sword kill ( metal )",
  "刀 構え 型 チャキーン": "sword Stance Type Chakin",
  "刀 構え 握り カチャ": "sword Stance grip Katya",
  "刀 納刀": "sword Sheathing the sword",
  "列車 渓谷 走行音": "train Valley Running noise",
  "列車 渓谷 風": "train Valley wind",
  "列車　はためく布": "train　Fluttering cloth",
  "列車　イベントサム戦 斬り飛ばし〜吹き飛ばされ": "train　Event Sam Battle Slashing ~ Blown away",
  "列車　イベントサム戦　列車後部着地": "train　Event Sam Battle　Landing at the rear of the train",
  "列車　イベントサム戦　斬り飛ばし〜追撃": "train　Event Sam Battle　Slash ~ Pursuit",
  "列車　イベントサム戦　鍔迫り合い": "train　Event Sam Battle　group of close competitors",
  "列車　揺れる鎖": "train　Swinging Chains",
  "列車走行音　停止": "Train running sound　Stop",
  "列車走行音　停止　※不要": "Train running sound　Stop * Not required",
  "列車走行音　開始": "Train running sound　start",
  "列車走行音　開始　※不要": "Train running sound　Start * Not required",
  "効果音 HDR用 大砲の着弾、手榴弾爆発など重要で印象づけたい発音はここへ。": "Sound effects For HDR Important pronunciations that you want to impress, such as those of a cannon shot hitting or a grenade exploding, go here .",
  "効果音 基本バス seバスのレベルによってダッキングされます": "Sound effects Basic Bus Ducked according to the level of the SE bus",
  "動作 スライディング　大": "Operation Sliding Large",
  "動作 スライディング　小": "Operation Sliding Small",
  "動作 掴む": "Operation grab",
  "動作 衣擦れ 中": "Operation Rubbing clothes Medium",
  "動作 衣擦れ 小": "Operation Rubbing clothes small",
  "動作 風切り　ジャンプ": "Operation Wind cutting　Jump",
  "地下下水": "Underground sewage",
  "地面　燃え": "ground　Burning",
  "地面　燃える": "ground　Burning",
  "塔　倒壊": "Tower collapses",
  "塔　倒壊揺れ": "Tower collapse shaking",
  "墜落": "Crash",
  "壁割れ崩れ": "Wall crack collapse",
  "壊れ　ガラス窓割れる　中　ダメージ編集": "Broken　Glass window breaking medium damageEdit",
  "壊れ物　車　持ち上げる": "Lifting a fragile car",
  "壊れ物　車　跳ねる": "Fragile car bounce",
  "大統領を抱えるサンダウナーにズーム": "Zoom into Sundowner holding the President",
  "奪　引き出す": "Take away",
  "奪　手を突っ込む": "Thrust the snatcher",
  "奪　握りつぶす": "Snatch and crush",
  "室外機": "Outdoor unit",
  "容量確保用ダミー": "Dummy for securing capacity",
  "小刀 ": "Small knife ",
  "屋根崩壊": "Roof collapse",
  "屋根落下時軋み": "Roof creaking when falling",
  "岩　落下　大": "Large rock fall",
  "建物　燃える": "building　Burning",
  "建物　燃える ストップ": "building　Burning stop",
  "強制無線　終了　雷電モーション m1001": "Forced Radio　end　Raiden Motion M1001",
  "強制無線　開始　雷電モーション m1000, m1004": "Forced Radio　start　Raiden Motion m1000, m1004",
  "必殺そのた": "Killer Other",
  "戦車　主砲　爆発音": "tank　Main gun　Explosion",
  "戦車　主砲　通過音": "tank　Main gun　Passing sound",
  "戦車　主砲発射": "tank　Main gun firing",
  "戦車　機関銃　発射": "tank　Machine gun　firing",
  "戦闘終了のムービー１": "End of battle movie 1",
  "戦闘途中のリアルタイムデモ": "Real-time demo during battle",
  "手榴弾　ピン抜く": "Grenade　Pull out the pin",
  "手榴弾　取り出す": "Grenade　Take out",
  "手榴弾　床に落ちる": "Grenade　Fall to the floor",
  "手榴弾　爆発": "Grenade　explosion",
  "挑発": "Taunt",
  "攻撃　キック　HI": "attack　kick　HI",
  "攻撃　キック　LO": "attack　kick　L.O.",
  "攻撃　パンチ　HI": "attack　punch　HI",
  "攻撃　パンチ　LO": "attack　punch　L.O.",
  "敵　ステルス迷彩　オフ": "Enemy Stealth Camouflage　off",
  "敵だ！": "It's the enemy !",
  "敵のバトルボイス　台詞など、戦闘中にハッキリ聴かせたいものを通す。bgmとその他seをダッキング": "Enemy Battle Voices　Pass through dialogue and other things you want to hear clearly during battle. Duck background music and other sound effects .",
  "敵のバトルボイス　汎用メイン　通常の気合い、掛け声はここに": "Enemy Battle Voices　General-purpose main　The usual spirit and cheers are here",
  "敵キャラ　機械　汎用": "Enemy Character　machine　General purpose",
  "斬撃　可能": "Slash　Yes",
  "旧市街地　スライダー登場": "Old Town　Slider appears",
  "旧市街地　環境音": "Old Town　Ambient Sound",
  "月光　!発見声": "moonlight　! Discovery Voice",
  "月光　?疑問声": "moonlight　? Questions",
  "月光　ジャンプ着地": "moonlight　Jump Landing",
  "月光　ジャンプ着地　遠距離用": "moonlight　Jump Landing　For long distance",
  "月光　ジャンプ開始": "moonlight　Start Jumping",
  "月光　ジャンプ開始　遠距離用": "moonlight　Start Jumping　For long distance",
  "月光　ダメージ　大": "moonlight　High damage",
  "月光　ダメージ　小": "moonlight　Small damage",
  "月光　ダメージ　燃料排出": "moonlight　damage　Fuel Emissions",
  "月光　ダメージ　燃料排出 止める": "moonlight　damage　Fuel Emissions stop",
  "月光　ダメージ　破壊": "moonlight　damage　destruction",
  "月光　ボディの揺れ": "moonlight　Body sway",
  "月光　体当たり": "moonlight　Body slam",
  "月光　倒れ時雄叫び": "moonlight　Roar when falling",
  "月光　刀の爪はじき　": "moonlight　Sword Claw Flick　",
  "月光　動作音": "moonlight　Operation noise",
  "月光　地面から　足を引き抜く": "moonlight　From the ground　Pull out the leg",
  "月光　地面に足が突き刺さる": "moonlight　Feet pierce the ground",
  "月光　地面足ささり中のもがき": "moonlight　Struggling with feet on the ground",
  "月光　崩れ落ち軋み音": "moonlight　The sound of something collapsing and creaking",
  "月光　崩れ衝撃音": "moonlight　Collapse impact sound",
  "月光　待機　駆動音": "moonlight　stand-by　Driving sound",
  "月光　断末魔": "moonlight　Death throes",
  "月光　死亡時　爆発": "moonlight　Death　explosion",
  "月光　死亡時　電気": "moonlight　Death　electricity",
  "月光　爆発　小": "moonlight　Small explosion",
  "月光　登場　セミ鳴き声": "moonlight　Appearance　Cicadas chirping",
  "月光　稼働停止　中": "moonlight　Out of service",
  "月光　稼働停止　大": "moonlight　Major outage",
  "月光　稼働開始　中": "moonlight　Now in operation",
  "月光　稼働開始　大": "moonlight　Start of operation",
  "月光　稼働開始　小": "moonlight　Start of operation",
  "月光　稼働開始　小2": "moonlight　Start of operation Small 2",
  "月光　触手 引っ張る": "moonlight　Tentacles pull",
  "月光　触手 引っ張る とめる": "moonlight　Tentacles pull Stop",
  "月光　触手　出現": "moonlight　Tentacles　Appearance",
  "月光　触手　収納": "moonlight　Tentacles　Storage",
  "月光　触手　叩きつけ": "moonlight　Tentacles　Slam",
  "月光　触手　引き抜く": "moonlight　Tentacles　Pull out",
  "月光　触手　振りまわし": "moonlight　Tentacles　Swinging around",
  "月光　触手　突き刺さり": "moonlight　Tentacles　Piercing",
  "月光　触手　風切り": "moonlight　Tentacles　Wind cutting",
  "月光　起き上がり": "moonlight　Getting up",
  "月光　足での掴み音": "moonlight　Foot grabbing noises",
  "月光　足地面ささり中のもがき　止める": "moonlight　Struggling with feet stuck in the ground　stop",
  "月光　足振り　風切り　中 ": "moonlight　Leg swing　During wind cutting ",
  "月光　足振り　風切り　大": "moonlight　Leg swing　Large windbreaker",
  "月光　足振り　風切り　小": "moonlight　Leg swing　Small windbreaker",
  "月光　足音　もがき": "moonlight　footsteps　Struggling",
  "月光　足音　停止時": "moonlight　footsteps　When stopped",
  "月光　足音　歩き": "moonlight　footsteps　Walking",
  "月光　足音　走り": "moonlight　footsteps　Running",
  "月光　踏みつけ": "moonlight　Trampling",
  "月光　蹴りヒット": "moonlight　Kick hit",
  "月光　蹴り足擦り": "moonlight　Kick and rub",
  "月光　転倒ジタバタ時": "moonlight　When falling and struggling",
  "月光　雄叫び　イベント用　半径1km同ボリューム": "moonlight　roar　For events, 1km radius and same volume",
  "月光　雄叫び　準備動作時等": "moonlight　roar　During preparation operations, etc.",
  "月光　頭　刀ねじられ": "Moonlight Head Sword Twisted",
  "月光　頭　刀突き刺され": "Moonlight Head Sword Stabbed",
  "月光　首の回転停止": "moonlight　Neck rotation stopped",
  "月光　首の回転開始": "moonlight　Neck rotation begins",
  "月光引きずられ用 雷電擦れ音": "For moonlight dragging Thunder and lightning rustling",
  "月光登場 コンテナ": "Moonlight Appears container",
  "木　ホロウ　壊れ": "Wood Hollow　Broken",
  "木　ホロウ　壊れ　複数": "Wood Hollow　Broken　multiple",
  "木　中空　落下　中": "Tree Hollow　Falling",
  "木　壊れ 中": "Broken Tree Medium",
  "木　壊れ　小": "Small broken wood",
  "木　破片　落下": "Wood chips　Fall",
  "木　破片　落下　中": "Wood chips　Falling",
  "木　空洞　落下": "Tree Hollow　Fall",
  "木　落下": "Tree Fall",
  "果物　落下": "fruit　Fall",
  "橋 河入口": "bridge River entrance",
  "橋　地鳴り": "Bridge rumble",
  "橋　爆発中 ": "Bridge exploding ",
  "橋　爆発小": "Bridge Explosion Small",
  "橋かたむき": "Bridge tilt",
  "橋崩れ　大": "Bridge collapse",
  "橋崩壊": "Bridge collapse",
  "橋落ち　水しぶき": "Bridge collapse　Splash",
  "機械　落下　中": "machine　Falling",
  "機銃　発射": "Machine gun　firing",
  "武器　爆発": "weapon　explosion",
  "武器アイテム出現時　ステルス迷彩　オフ": "When a weapon item appears　Stealth Camouflage　off",
  "武器アイテム消失時　ステルス迷彩　オン": "When a weapon item disappears　Stealth Camouflage　on",
  "武器メニュー　カーソル音　上下": "Weapon menu cursor sound　Up and down",
  "武器メニュー　カーソル音　左右": "Weapon menu cursor sound　Left and right",
  "武器メニュー　リペアパーツ　装備": "Weapons Menu Repair Parts　Equipment",
  "段ボール": "cardboard",
  "段ボール 複数 壊れ": "cardboard multiple Broken",
  "段ボール　落下": "cardboard　Fall",
  "水路": "Waterway",
  "水門　閉じる": "Watergate　close",
  "決定音大": "Decision sound loud",
  "決定音小": "Small decision sound",
  "波止場 環境音": "Wharf Ambient Sound",
  "波止場　環境音　ストップ": "Wharf　Ambient Sound　stop",
  "泥": "mud",
  "浜辺　ステルスサイボーグ登場": "beach　Stealth Cyborg Appears",
  "滴る水音　中": "Dripping water sound",
  "滴る水音　小": "Dripping water sound small",
  "演出中　サムvoice＆se　ストップ": "Currently being performed　Samvoice & se　stop",
  "無線　CALL　表示": "wireless　CALL　display",
  "無線　顔　ウィンドウ表示": "Wireless Face Window Display",
  "無線　顔　ウィンドウ非表示": "Wireless Face Window Hidden",
  "無線　顔　表示": "Wireless Face Display",
  "無線　顔　非表示": "Wireless Face Hiding",
  "爆発　　（ソフト：爆発時トリガー）": "Explosion ( Soft: Trigger on Explosion )",
  "爆発中": "Exploding",
  "爆発小": "Small explosion",
  "環境ボイス": "Environmental Voices",
  "瓦礫": "rubble",
  "発砲": "Firing",
  "白雷電用　標準刀": "For White Lightning　Standard sword",
  "盾閉じる　風切りとサーボ": "Shield Close　Wind and servos",
  "石　切断": "Stone cutting",
  "石油プラント": "Oil Plant",
  "砂利": "gravel",
  "砂煙　天井崩れ": "Sand dust　Ceiling collapse",
  "磁グレネード　地面ヒット": "Magnetic Grenade　Ground hit",
  "船　汽笛": "Ship whistle",
  "街　戦闘中 　環境音　ストップ": "In town 　Ambient Sound　stop",
  "街　戦闘中　環境音": "In town　Ambient Sound",
  "装甲車　アイドリング": "Armored vehicles　Idling",
  "装甲車　ハッチ閉まる": "Armored vehicles　The hatch closes",
  "装甲車　ハッチ開く": "Armored vehicles　Hatch open",
  "装甲車　リア閉まる": "Armored vehicles　Rear closes",
  "装甲車　リア開く": "Armored vehicles　Rear open",
  "装甲車　火花": "Armored vehicles　spark",
  "装甲車　爆発": "Armored vehicles　explosion",
  "装甲車　走行音": "Armored vehicles　Running noise",
  "西瓜　大　斬る": "Watermelon Slice",
  "西瓜　小　斬る": "Cutting watermelon into small pieces",
  "観覧車　本体　切断後　落下": "Ferris Wheel　Main unit　After cutting　Fall",
  "観覧車　本体　崩壊": "Ferris Wheel　Main unit　Collapse",
  "観覧車　足　切断後　落下": "Ferris wheel after leg amputation　Fall",
  "観覧車　足　壊れ": "Ferris wheel broken leg",
  "赤燐グレネード 地面ヒット": "Red phosphorus grenade Ground hit",
  "赤燐グレネード　爆発": "Red phosphorus grenade　explosion",
  "足音 歩く (属性)": "footsteps Walking ( attribute )",
  "足音 走る (属性)": "footsteps Run ( attribute )",
  "足音　走り": "footsteps　Running",
  "踏みつけ": "Trampling",
  "車　爆発　燃え": "Car Explosion　Burning",
  "車　設置時から燃える （効果埋め込み）": "Burns from the moment the car is installed ( Effect embedding )",
  "通常": "usually",
  "重装兵　ダウン　中": "Heavy Trooper　Down",
  "重装兵　ダウン　小": "Heavy Trooper　Down Small",
  "重装兵　衣擦れ　中": "Heavy Trooper　Rubbing clothes",
  "重装兵　衣擦れ　大": "Heavy Trooper　Clothes Rubbing",
  "重装兵　衣擦れ　小": "Heavy Trooper　Clothes Rubbing Small",
  "重装兵　足音　擦り": "Heavy Trooper　footsteps　Rubbing",
  "重装兵　足音　歩き": "Heavy Trooper　footsteps　Walking",
  "重装兵　足音　走り": "Heavy Trooper　footsteps　Running",
  "金属 フェンス ": "metal fence ",
  "金属　空洞　落下　中": "metal　cavity　Falling",
  "金属　空洞　落下　大": "metal　cavity　Large fall",
  "金属ソリッド　壊れ　中": "Metal Solid　Broken",
  "金属パイプ　壊れ　中": "Metal Pipe　Broken",
  "金属パイプ　壊れ　小": "Metal Pipe　Broken Small",
  "金属ホロウ　壊れ　小": "Metal Hollow　Broken Small",
  "金属ホロウ　壊れ　小　複数": "Metal Hollow　Broken small multiple",
  "金属壊れ　(金属中空+パイプS)　屋台等": "Metal broken　( Hollow metal + pipe S )　Food stalls, etc.",
  "金属空洞　壊れ　中": "Metal Cavity　Broken",
  "金属落下　中": "Metal falling",
  "金属落下　小": "Small metal fall",
  "鉄網　壊れ　中": "Iron net　Broken",
  "銃弾　跳弾　コンクリート": "bullet　Ricochet　concrete",
  "銃弾　跳弾　土": "bullet　Ricochet Earth",
  "銃弾　跳弾　木": "bullet　Ricochet Tree",
  "銃弾　跳弾　水": "bullet　Ricochet Water",
  "銃弾　跳弾　通過": "bullet　Ricochet　Passing",
  "銃弾　跳弾　鉄": "bullet　Ricochet Iron",
  "銃構え": "Gun Ready",
  "間接　戻り 中": "Indirect　return Medium",
  "間接　戻り 小": "Indirect　return small",
  "間接　開始 中": "Indirect　start Medium",
  "間接　開始 小": "Indirect　start small",
  "雑誌": "magazine",
  "雷電　 高周波ブレード": "Raiden　 High Frequency Blade",
  "雷電　刀　キャッチ": "Raiden Sword Catch",
  "雷電　標準刀": "Raiden　Standard sword",
  "雷電　装甲車HIT　モンスーン戦": "Raiden　Armored Car HIT　Monsoon Battle",
  "雷電用　アーマーブレーカー": "For lightning　Armor Breaker",
  "雷電用　サム　高周波ブレード": "For lightning　Sam　High Frequency Blade",
  "雷電用　スタンブレード": "For lightning　Stun Blade",
  "雷電用　スネークブレード": "For lightning　Snake Blade",
  "雷電用　フォックスブレード": "For lightning　Fox Blade",
  "雷電用　マチェット": "For lightning　Machete",
  "雷電用　ロングブレード": "For lightning　Long Blade",
  "雷電用　木刀": "For lightning　Wooden sword",
  "雷電用　木刀 ": "For lightning　Wooden sword ",
  "雷電用　標準刀": "For lightning　Standard sword",
  "電磁グレネード　爆発": "Electromagnetic Grenade　explosion",
  "電磁グレネード　痺れ音": "Electromagnetic Grenade　Numbness sound",
  "電磁バリア　解除": "Electromagnetic Barrier　Cancellation",
  "電磁バリア　開く （効果埋め込み）": "Electromagnetic Barrier　open ( Effect embedding )",
  "電線　火花": "Electric wire　spark",
  "飛行　ホバリング　ピヨリ　復帰時　上昇 (ソフトトリガー)": "Flying　Hovering　Piyori　Upon return　Ascending ( Soft Trigger )",
  "飛行　ホバリング　ピヨリ時　急下降 (ソフトトリガー)": "Flying　Hovering　When you're standing still　Sudden drop ( soft trigger )",
  "飛行　ホバリング　（ソフト：OBJ生成時トリガー）": "Flying　Hovering ( Soft: Triggered when OBJ is generated)",
  "飛行　ホバリング　（ソフト：OBJ生成時トリガー） にぎやかし用": "Flying　Hovering ( Soft: Triggered when OBJ is generated) For entertainment purposes",
});
